// ---- UI dictionary (English-only build) --------------------------------------
// Course data (curricula, lessons) lives in lib/courses. The Arabic UI option
// was removed by request; the Lang type is kept so call sites stay unchanged.

export type Lang = "en";

const en = {
  nav: {
    courses: "Courses",
    bundle: "Bundle",
    instructor: "Instructor",
    blog: "Journal",
    faq: "FAQ",
    contact: "Contact",
    login: "Log in",
    logout: "Log out",
    dashboard: "My learning",
    account: "Account settings",
    studio: "Studio",
    startFree: "Start free ✦",
    allCourses: "All courses →",
    training: "Agencies",
    roleTag: "· Visual Direction & AI Workflow",
  },

  offer: {
    text: "Launch offer — the AI Production Stack for EGP 5,200 instead of 6,000",
    ends: "Offer ends in",
    cta: "Grab it",
    days: "d",
    hours: "h",
    mins: "m",
    secs: "s",
  },

  common: {
    enroll: "Enroll now ✦",
    enrollFree: "Start learning free ✦",
    continueLearning: "Continue learning",
    viewCourse: "View course",
    lessons: "lessons",
    lesson: "Lesson",
    hours: "hours",
    modules: "modules",
    projects: "projects",
    level: "Level",
    students: "students",
    graduates: "graduates",
    academies: "academies",
    free: "Free",
    premium: "Premium",
    save: "Save",
    enrolled: "Enrolled ✓",
    completed: "Completed",
    inProgress: "In progress",
    notStarted: "Not started",
    by: "by",
    back: "Back",
    close: "Close",
    comingSoon: "Coming soon",
    downloadPng: "Download PNG",
    minutesShort: "m",
    hoursShort: "h",
    freePreview: "Free preview",
    locked: "Locked",
    rating: "rating",
    reviewsWord: "reviews",
    of: "of",
    home: "Home",
  },

  home: {
    kicker: "Tarek — not another course site",
    heroA: "Own the craft.",
    heroI: "Out-design",
    heroB: "everyone.",
    heroSub:
      "The software courses? Free — all of them, complete start to finish. The AI production courses? Premium, expensive, and worth it. That's the whole business model.",
    ctaPrimary: "Grab the free courses ✦",
    ctaSecondary: "Browse courses",
    heroCardTag: "Free drop — full course",
    heroStickers: ["4 free courses", "AI = the money skill", "zero filler"],
    scroll: "scroll",
    marquee: ["Photoshop — free", "Illustrator — free", "After Effects — free", "Premiere Pro — free", "AI Photoshoot — premium", "AI Video — premium", "Real projects", "No filler", "Zero → Pro"],
    statsLabel: "The record",
    stats: {
      graduates: "graduates taught",
      academies: "academies teach his method",
      hours: "hours of zero-filler curriculum",
      lessons: "hands-on lessons",
    },
    manLabel: "The deal",
    freeTitle: "The software is free. Yes, actually.",
    freeBody: "Photoshop, Illustrator, After Effects, Premiere Pro — complete courses with projects, quizzes and reviewed final projects. EGP 0. Nobody should be gatekeeping tools in 2026.",
    freeTag: "EGP 0 — forever",
    paidTitle: "The AI is the money skill. Priced like one.",
    paidBody: "AI Photoshoot and AI Video are what clients pay serious budgets for right now. One approved brief covers the course — and the pricing lessons are inside. That's the math.",
    paidTag: "Pays for itself",
    coursesLabel: "The drops",
    coursesTitleA: "Six drops.",
    coursesTitleI: "One standard",
    coursesTitleB: ".",
    coursesNote: "Free means actually complete — portfolio piece included. Premium means it actually earns. 3–5 hours each, zero filler.",
    featuredLabel: "Featured drop",
    featuredNote: "If you're here to earn, start here.",
    featuredCta: "Open the course ✦",
    featuredBrowse: "Browse everything",
    econLabel: "The economics",
    econTitleA: "Priced like an",
    econTitleI: "investment",
    econTitleB: ", not a course.",
    econ: [
      { n: "50,000+", u: "EGP", l: "what one studio photoshoot day costs a brand" },
      { n: "2,800", u: "EGP", l: "what the complete AI Photoshoot course costs — once, forever" },
      { n: "×17", u: "", l: "the gap between them — that margin is the service you'll sell" },
    ],
    storyLabel: "Featured story",
    storyQuote:
      "I finished the AI stack on a Friday. Two weeks later I quoted my first spot for more than my monthly salary — and the client didn't blink. The pricing lesson alone paid for everything.",
    storyName: "Khaled Emad",
    storyRole: "Freelance designer → AI production",
    storyChips: ["First paid brief: 3 weeks", "Now freelancing full-time", "AI Production Stack graduate"],
    beforeAfter: "hover — before / after",
    outcomesLabel: "Proof",
    outcomesTitleA: "Outcomes,",
    outcomesTitleI: "not promises",
    outcomesTitleB: ".",
    outcomes: [
      { n: 1200, s: "+", l: "students taught across four academies" },
      { n: 78, s: "%", l: "of finishers land paid work within 3 months" },
      { n: 21, s: "", l: "days on average to a first paid brief after the AI stack" },
      { n: 96, s: "%", l: "completion rate — 3–5 hour courses actually get finished" },
    ],
    galleryLabel: "Made with the method",
    communityNote:
      "Every student joins the private WhatsApp room — critiques, gigs and new drops land there first.",
    trustChips: ["7-day money-back", "Personal WhatsApp support", "Lifetime access", "Taught in Arabic"],
    instructorChipsLabel: "Rooms his work has lived in",
    instructorChips: ["Osolutions — Art Team Lead", "Bundle IMS — Kuwait", "Rolls-Royce KV", "Geely / GWM", "SOIC — Cinema", "EDUX Academy", "Raya Academy", "Prepd"],
    pathLabel: "The method",
    pathTitleA: "Zero →",
    pathTitleI: "pro",
    pathTitleB: ", in five beats.",
    pathNote: "Every course, same arc.",
    path: [
      { t: "Learn", d: "Working file open. Watch, pause, do." },
      { t: "Practice", d: "Drills after every module." },
      { t: "Project", d: "Real briefs → portfolio pieces." },
      { t: "Checkpoint", d: "Quizzes that test decisions." },
      { t: "Ship", d: "A reviewed piece that gets you hired." },
    ],
    whyLabel: "Why Tarek",
    whyTitleA: "Courses built like",
    whyTitleI: "campaigns",
    whyTitleB: ".",
    why: [
      { t: "A director, not a narrator", d: "Every lesson comes from live client work — campaigns, identities, films that shipped. You learn decisions, not buttons." },
      { t: "3–5 hours, zero filler", d: "Courses are edited like films. If a minute doesn't change how you work, it's cut." },
      { t: "Projects over playback", d: "Every module ends with your hands on a real brief. Finishing means a portfolio, not a watch history." },
      { t: "Arabic-friendly, world-standard", d: "Taught for the MENA market, benchmarked against global studio craft." },
    ],
    instructorLabel: "The instructor",
    instructorTitleA: "Taught by a working",
    instructorTitleI: "art director",
    instructorTitleB: ".",
    instructorBio:
      "Mohamed Tarek leads brand, campaign and motion work across Egypt, Saudi Arabia and Kuwait — and has taught 1,200+ students across four academies. This school is his method, distilled: the exact workflows his teams use on paying briefs.",
    instructorCta: "Meet the instructor",
    brandsNote: "Brands his work has served",
    bundleLabel: "The AI stack",
    bundleCta: "Grab the stack ✦",
    bundleNote: "vs. buying separately",
    testimonialsLabel: "Student words",
    testimonialsTitleA: "They came for a tool.",
    testimonialsTitleI: "They left with a craft",
    testimonialsTitleB: ".",
    faqLabel: "Questions",
    faqTitle: "Before you ask —",
    faqCta: "All questions answered",
    finalLabel: "Begin",
    finalTitleA: "Four courses are",
    finalTitleI: "free",
    finalTitleB: ". What's your excuse?",
    finalSub: "Start Photoshop Mastery right now — the complete course, final project included. No card, no trial, no catch.",
    finalCta: "Start free now ✦",
    finalAlt: "or browse all courses",
  },

  catalog: {
    metaTitle: "Courses — Free Software Craft + Premium AI Production",
    kicker: "The drops",
    titleA: "Choose your",
    titleI: "craft",
    titleB: ".",
    sub: "Four software courses, completely free. Two premium AI tracks that pay for themselves. All: 3–5 hours, projects, quizzes, final projects.",
    all: "All",
    filterDesign: "Design",
    filterMotion: "Motion & Video",
    filterAi: "AI Production",
    bundleCard: "The AI Production Stack",
    bundleCardSub: "AI Photoshoot + AI Video — one enrollment, one pipeline",
    empty: "No courses in this filter yet.",
    searchPh: "Search courses, tools, skills…",
    filterFree: "Free",
    filterPremium: "Premium",
    popular: "Most popular",
    recommended: "Recommended",
    results: "results",
  },

  course: {
    breadcrumbCourses: "Courses",
    heroIncludes: "This course includes",
    includesItems: [
      "Lifetime access, updates included",
      "Practical projects & working files",
      "Checkpoint quizzes",
      "Final project with a personal review",
      "Downloadable resources",
      "WhatsApp support from the instructor",
    ],
    whatYouLearn: "What you walk out with",
    pathLabel: "Learning path",
    curriculumLabel: "Curriculum",
    curriculumNote: "Editorial index — every lesson, every minute, no padding.",
    projectsLabel: "Practical projects",
    resourcesLabel: "Downloadable resources",
    finalProjectLabel: "Final project",
    deliverables: "You deliver",
    outcomeLabel: "The outcome",
    outcomeTitle: "Finish it. Ship it.",
    outcomeNote:
      "Complete every lesson, pass the checkpoint quiz and submit the final project — you leave with a reviewed portfolio piece, not just a watch history.",
    instructorLabel: "Your instructor",
    reviewsLabel: "Student reviews",
    faqLabel: "Course FAQ",
    enrollTitle: "Enroll in this course",
    bundleHint: "Part of the AI Production Stack —",
    bundleHintCta: "see the bundle",
    guarantee: "7-day money-back guarantee — no forms, one WhatsApp message.",
    startFreeNote: "Free forever. No card required.",
    alreadyEnrolled: "You're enrolled —",
    goToCourse: "go to the course →",
    audienceLabel: "Who it's for",
    toolsLabel: "Tools covered",
    relatedLabel: "Pairs well with",
    viewingNow: "designers on this page right now",
    showcaseLabel: "Made with this course",
    showcaseNote: "Straight from the exact pipeline you're about to learn — real client output, no cherry-picking.",
  },

  bundle: {
    metaTitle: "The AI Production Stack — AI Photoshoot + AI Video",
    kicker: "The AI stack",
    includes: "Two courses. One pipeline.",
    note: "The complete camera-less campaign stack — stills, motion, and the pricing to sell both.",
    totalRuntime: "total runtime",
    totalLessons: "lessons",
    projectsNote: "6 practical projects + 2 reviewed final projects — a portfolio, not a playlist",
    cta: "Enroll in the stack ✦",
    vs: "bought separately",
    save: "you save",
  },

  auth: {
    loginTitle: "Welcome back.",
    loginSub: "Your courses, progress and projects are waiting.",
    registerTitle: "Start your craft.",
    registerSub: "One account — every course, project and review lives here.",
    name: "Full name",
    namePh: "e.g. Salma Ibrahim",
    email: "Email",
    emailPh: "you@example.com",
    password: "Password",
    passwordPh: "••••••••",
    loginBtn: "Log in →",
    registerBtn: "Create account →",
    orRegister: "New to Tarek?",
    orLogin: "Already have an account?",
    registerLink: "Create an account",
    loginLink: "Log in",
    demoNote: "Demo platform: your account lives in this browser only — no server, no spam, no password stored.",
    previewLabel: "Or jump straight in",
    previewStudent: "Preview as student",
    previewAdmin: "Preview as admin",
    accountType: "Joining as",
    typeStudent: "A student",
    typeTeam: "An agency / team",
    teamNote: "Team programs have their own fast lane — a custom plan, on-site or live online.",
    teamCta: "Open team training →",
    errName: "Please enter your name.",
    errEmail: "Please enter a valid email.",
  },

  checkout: {
    metaTitle: "Checkout",
    kicker: "Checkout",
    title: "Almost in.",
    orderLabel: "Your order",
    payLabel: "Payment method",
    instapay: "InstaPay",
    vodafone: "Vodafone Cash",
    manualNote:
      "Transfer the amount, then tap the button below — send your payment screenshot on WhatsApp and your access is activated personally, usually within minutes.",
    gatewaysSoon: "Card payments (Paymob · Fawry · valU) — arriving soon.",
    total: "Total",
    confirmBtn: "I've paid — confirm on WhatsApp ✦",
    freeBtn: "Enroll free — instant access ✦",
    backTo: "Back to course",
    secure: "Manual, human-verified enrollment — the same flow 1,200+ students used.",
    loginFirst: "Log in or create an account to complete enrollment.",
  },

  success: {
    enrollTitle: "You're in.",
    enrollSub: "Your enrollment is confirmed. Your first lesson is one click away — momentum matters, start now.",
    goDashboard: "Go to my learning →",
    startCourse: "Start the course ✦",
  },

  dash: {
    metaTitle: "My Learning",
    kicker: "Student dashboard",
    greetingM: "Good morning",
    greetingA: "Good afternoon",
    greetingE: "Good evening",
    subEmpty: "Your desk is clear. Pick a course and make it messy.",
    sub: "Pick up exactly where you left off.",
    accountCta: "Account settings",
    goalLabel: "Weekly goal",
    goalOf: "of",
    goalUnit: "h this week",
    goalEdit: "Adjust",
    goalHint: "hours per week",
    goalDone: "Goal cleared — monster. ✦",
    coursesLabel: "My courses",
    tabActive: "Active",
    tabArchived: "Archived",
    archive: "Archive",
    unarchive: "Restore",
    archivedEmpty: "Nothing archived — everything's in play.",
    assignmentsLabel: "My assignments",
    aStatus: {
      done: "Completed",
      review: "In review",
      progress: "In progress",
      upcoming: "Upcoming",
    },
    qualified: "Qualified",
    sessionsLabel: "Upcoming sessions",
    sessionJoin: "Join room",
    sessionBy: "with Mohamed Tarek",
    statsLabel: "Study statistics",
    statsUnit: "minutes / day",
    statsEmpty: "Finish a lesson and the bars start moving.",
    calendarLabel: "Calendar",
    doubtLabel: "Ask a doubt",
    doubtPh: "Stuck on a lesson? Type your question…",
    doubtSend: "Send",
    doubtNote: "Lands straight in the instructor's WhatsApp.",
    continueLabel: "Continue",
    enrolledLabel: "My courses",
    progressWord: "complete",
    browseCta: "Browse the catalog →",
    statsLessons: "lessons completed",
    statsMinutes: "minutes of craft",
    statsQuizzes: "quizzes cleared",
    quizReady: "Checkpoint quiz ready",
    finalStep: "Final step: pass the checkpoint quiz",
  },

  learn: {
    curriculum: "Curriculum",
    nowPlaying: "Now playing",
    comingSoon: "Video — publishing soon",
    playerNote: "Lessons are being filmed and published module by module. Progress tracking, resources and quizzes are live now.",
    markDone: "Mark lesson complete",
    markedDone: "Completed ✓",
    next: "Next lesson →",
    prev: "← Previous",
    resources: "Resources",
    resourceGet: "Download",
    resourceLocked: "Enroll to download",
    quizTitle: "Checkpoint quiz",
    quizIntro: "Six decisions. Pass 5 to clear the checkpoint — this is where knowing becomes owning.",
    quizStart: "Start the quiz →",
    quizQuestion: "Question",
    quizCheck: "Check answers",
    quizPassed: "Checkpoint cleared ✓",
    quizFailed: "Not yet — review the misses and retry.",
    quizRetry: "Retry",
    quizScore: "Your score",
    progressLabel: "Course progress",
    completedTitle: "Course complete — now go get paid.",
    boardTab: "Notes board",
    boardAdd: "Note",
    boardClear: "Clear board",
    boardClearConfirm: "Clear all notes from this course's board?",
    boardEmpty: "Your board. Drop notes, ideas, timestamps — a FigJam-style page that lives with this course.",
    boardPlaceholder: "Type a note…",
    boardDelete: "Delete note",
    boardHint: "Drag notes anywhere — saved automatically.",
    boardPen: "Pen — draw on the board",
    boardPenHint: "Pen on — draw anywhere.",
    boardErase: "Eraser — remove strokes",
    boardEraseHint: "Eraser on — drag over a stroke to remove it.",
    boardHand: "Hand — move around the board",
    boardHandHint: "Hand on — drag to pan the board.",
    backToDash: "← My learning",
    enrollGate: "Enroll to open the full course",
    enrollGateSub: "The first lessons are free previews — the rest unlocks with enrollment.",
    finalProjectTab: "Final project",
    overviewTab: "Overview",
  },

  profile: {
    metaTitle: "Profile",
    kicker: "Student profile",
    memberSince: "Learning since",
    editName: "Display name",
    phone: "Phone (WhatsApp)",
    changePhoto: "Change photo",
    photoNote: "JPG or PNG — stored in your browser only.",
    saveBtn: "Save changes",
    saved: "Saved ✓",
    dangerLabel: "Session",
    logoutBtn: "Log out",
    resetBtn: "Reset all demo data",
    resetConfirm: "This clears your account, progress and quiz results from this browser. Sure?",
    statsLabel: "Your numbers",
  },

  downloads: {
    metaTitle: "Downloads",
    kicker: "The vault",
    title: "Downloads",
    sub: "Working files, cheat sheets and templates from your enrolled courses.",
    empty: "Enroll in a course to unlock its resource vault.",
    perCourse: "From",
  },

  blogUi: {
    metaTitle: "Journal — Design Education, Career Paths & AI Production",
    kicker: "The journal",
    titleA: "Notes from the",
    titleI: "atelier",
    titleB: ".",
    sub: "Honest writing on learning design, career sequencing and AI production — from the desk, not the content calendar.",
    readMore: "Read →",
    minsRead: "min read",
    relatedCourse: "The course behind this article",
    backToBlog: "← All articles",
    faqInPost: "Quick answers",
  },

  faqPage: {
    metaTitle: "FAQ — Enrollment, Courses, Payments & Access",
    kicker: "Questions",
    titleA: "Everything you'd",
    titleI: "ask",
    titleB: ", answered.",
    sub: "Enrollment, payments, courses, tools — if it's not here, WhatsApp me directly.",
    stillCta: "Still curious? Talk to me →",
    items: [
      { q: "How do courses work at Tarek?", a: "Every course is 3–5 hours of focused video organized into modules, with drills, real projects, downloadable working files, checkpoint quizzes and a final project. Finish everything and you walk out with a reviewed portfolio piece — the thing that actually gets you hired." },
      { q: "Why are the courses so short?", a: "Because they're edited like films. Ten-hour courses are ten hours because nobody cut them. Tarek courses keep only the minutes that change how you work — the rest of your time goes into practice, which is where skill actually forms." },
      { q: "How do I pay from Egypt?", a: "InstaPay or Vodafone Cash: transfer, send the screenshot on WhatsApp, and your access is activated personally — usually within minutes. Card gateways (Paymob, Fawry, valU) are arriving soon." },
      { q: "Which courses are actually free?", a: "All four software courses — Photoshop, Illustrator, After Effects and Premiere Pro — complete with projects, quizzes and reviewed final projects, at EGP 0 forever. The two AI production tracks (EGP 2,800 and 3,200) are the premium courses, because they're the highest-earning skill we teach — and they include the pricing lessons to earn it back fast." },
      { q: "Do I get lifetime access?", a: "Yes. One payment, permanent access, all future updates to that course included." },
      { q: "What if the course isn't for me?", a: "7-day money-back guarantee. One WhatsApp message, no forms, no questions that matter." },
      { q: "Do I get something to show employers?", a: "Something better than a paper credential: finished, personally-reviewed portfolio projects from every course. Employers and clients hire from work, not certificates — Tarek is built around that truth." },
      { q: "Do I need a powerful computer?", a: "No. Every course is taught on mid-range hardware, with performance workarounds (like Premiere proxies) built into the curriculum." },
      { q: "Is the teaching in Arabic or English?", a: "Lessons are taught in Arabic with English tool vocabulary — the way MENA studios actually talk. The platform itself is fully bilingual." },
      { q: "Can I get training for my team or academy?", a: "Yes — corporate and academy programs run separately (on-site in Egypt, online elsewhere). Reach out via the contact page and I'll reply personally." },
    ],
  },

  admin: {
    metaTitle: "Studio",
    kicker: "The studio — admin",
    welcome: "Welcome back",
    sub: "Revenue, signups and course performance — the whole school on one desk.",
    range: "Last 14 days",
    statRevenue: "Total revenue",
    statStudents: "Students",
    statConversion: "Visit → enroll",
    statCourses: "Live courses",
    chartLabel: "Revenue",
    topLabel: "Top courses",
    topBy: "by revenue",
    signupsLabel: "Latest signups",
    youTag: "this browser",
    locationsLabel: "Where students learn from",
    reviewLabel: "Final projects waiting on you",
    reviewCta: "Review",
    controlsLabel: "Site controls",
    offerText: "Offer ribbon text",
    offerOn: "Show the offer ribbon",
    offerReset: "Restart the 7-day timer",
    save: "Save",
    saved: "Saved ✓",
    editCourses: "Edit courses",
    editorKicker: "The studio — course editor",
    editorTitle: "Every course, editable.",
    editorSub: "Prices, names, covers, fresh lessons — changes apply live across the whole site.",
    fTitle: "Course title",
    fShort: "Card name",
    fTagline: "Tagline",
    fPrice: "Price (EGP)",
    fCompare: "Compare-at (EGP)",
    fCover: "Cover image path / URL",
    addLessonLabel: "Add a video lesson",
    fLessonTitle: "Lesson title",
    fLessonMins: "Minutes",
    fLessonUrl: "Video URL (YouTube / MP4)",
    addLessonBtn: "Add lesson +",
    extraCount: "fresh drops added",
    resetCourse: "Reset this course",
    resetAll: "Reset all studio edits",
    edited: "Edited",
    open: "View page",
    backToStudio: "← Studio",
    localNote: "Studio demo: edits save in this browser and restyle the live site instantly — prices, cards, checkout, everything.",
    guard: "This desk belongs to the instructor.",
    guardSub: "Log in with the admin account — or preview the studio in one click.",
    guardCta: "Preview as admin ✦",
  },

  training: {
    kicker: "For agencies & teams",
    titleA: "Train the",
    titleI: "whole team",
    titleB: ".",
    sub: "Custom Tarek programs for agencies, studios and marketing teams — brand, campaign, motion and AI production. On-site in Egypt, live online everywhere else.",
    formTitle: "Request a team program",
    agency: "Company / agency name",
    pName: "Contact person",
    pNamePh: "Who I'll be talking to",
    pRole: "Their role / title",
    pRoles: ["CEO / Founder", "Marketing manager", "Creative / art director", "HR / L&D lead", "Team lead", "Other"],
    size: "Team size",
    sizes: ["2–5", "6–15", "16–50", "50+"],
    industry: "Industry",
    industries: ["Agency / studio", "Real estate", "F&B / hospitality", "Fashion / retail", "Tech / startup", "Education", "Other"],
    location: "Location",
    locations: ["Egypt", "Saudi Arabia", "UAE", "Kuwait", "Qatar", "Other"],
    website: "Website / portfolio link",
    modeLabel: "Delivery mode",
    modeEg: "🇪🇬 On-site or live online — your choice, since you're in Egypt.",
    modeIntl: "🌍 Live online — full program delivered remotely for teams outside Egypt.",
    submit: "Request the program →",
    note: "Opens your email app with everything pre-filled — I reply personally within 24 hours.",
    consultTitle: "Free strategy consultation",
    consultSub: "For CEOs, founders, owners and marketing managers: a free call — up to 60 minutes — on how AI production can cut your content costs and speed up your output. Happy to assist.",
    consultTag: "Free · up to 60 min",
    cName: "Your name",
    cRole: "Your role",
    cRoles: ["CEO", "Founder / owner", "Marketing manager", "Other executive"],
    cCompany: "Company",
    cContact: "Email or WhatsApp number",
    cTime: "Preferred time",
    cTimes: ["Morning", "Afternoon", "Evening"],
    cSubmit: "Book the free call →",
    cNote: "Booked over WhatsApp — you'll get a reply the same day.",
    tabProgram: "Team program",
    tabConsult: "Free consult · 60 min",
    tabHint: "Pick a lane — one form, two minutes.",
    bannerTag: "Tarek for business",
  },

  contact: {
    metaTitle: "Contact — Talk to the Instructor",
    kicker: "Contact",
    titleA: "Talk to a",
    titleI: "person",
    titleB: ". Me, specifically.",
    sub: "Enrollment help, team training, academy partnerships or just a question about your path — I answer personally, usually same-day.",
    waCta: "WhatsApp me →",
    emailCta: "Email me →",
    formName: "Your name",
    formEmail: "Your email",
    formTopic: "Topic",
    topics: ["Course question", "Enrollment / payment help", "Team or academy training", "Something else"],
    formMsg: "Your message",
    formSend: "Send message →",
    formNote: "Opens your email app with everything pre-filled.",
    trainingTitle: "Companies & academies",
    trainingNote: "Custom programs for teams — brand, campaign, motion and AI production. On-site in Egypt, online everywhere else.",
  },

  legal: {
    kicker: "Legal",
    updated: "Last updated",
    terms: {
      title: "Terms of Service",
      sections: [
        { h: "The service", p: "Tarek provides online design education: video lessons, projects, resources, quizzes and final-project reviews. Access to paid courses is granted per person after payment confirmation and is not transferable or shareable." },
        { h: "Enrollment & access", p: "Paid enrollments grant lifetime access to the purchased course, including future updates to that course. Free courses may be updated, extended or restructured at any time." },
        { h: "Acceptable use", p: "Course videos, files and resources are licensed to you personally. Redistributing, reselling, screen-recording for sharing, or uploading materials elsewhere terminates access without refund and may carry legal consequences." },
        { h: "Completion", p: "Course completion means all lessons finished, checkpoint quizzes passed and a final project submitted. Final projects receive a personal review from the instructor." },
        { h: "Refunds", p: "A 7-day money-back guarantee applies to paid courses — see the Refund Policy for the exact terms." },
        { h: "Changes", p: "These terms may be updated; continued use after changes constitutes acceptance. Material changes will be announced on the platform." },
      ],
    },
    privacy: {
      title: "Privacy Policy",
      sections: [
        { h: "What this demo stores", p: "This platform currently runs fully in your browser: your account name, email, course progress and quiz results are stored in your browser's local storage only. No server receives, processes or sells this data." },
        { h: "Payments", p: "Payments run through InstaPay, Vodafone Cash or (soon) licensed gateways. Tarek never sees or stores card numbers; payment confirmation happens via WhatsApp screenshots you choose to send." },
        { h: "Communication", p: "WhatsApp and email conversations are used solely to activate access, provide support and — only with your consent — share course updates." },
        { h: "Analytics", p: "If analytics are enabled, they are aggregate and anonymous: page views and course popularity, never personal learning data tied to your identity." },
        { h: "Your rights", p: "You can clear all locally-stored data anytime from your Profile page, and request deletion of any support-conversation history via WhatsApp or email." },
      ],
    },
    refunds: {
      title: "Refund Policy",
      sections: [
        { h: "The guarantee", p: "Every paid course carries a 7-day money-back guarantee, counted from access activation. If it isn't right for you, one WhatsApp message gets your money back — no forms, no friction." },
        { h: "How refunds work", p: "Send your enrollment details on WhatsApp within 7 days. Refunds are returned via the same method you paid (InstaPay / Vodafone Cash) within 3 business days." },
        { h: "Fair use", p: "The guarantee exists to remove risk, not to lend content: accounts that complete more than 60% of a course or download its full resource vault before requesting a refund may be reviewed individually." },
        { h: "Bundles", p: "Bundle refunds work identically within the 7-day window. Partial bundle refunds (keeping one course) are handled personally — just ask." },
      ],
    },
  },

  footer: {
    blurb: "Tarek is the online school of art director Mohamed Tarek — short, premium design courses that end in real projects, real skills and a real portfolio.",
    learnCol: "Learn",
    platformCol: "Platform",
    companyCol: "School",
    legalCol: "Legal",
    connectCol: "Connect",
    rights: "All rights reserved.",
    backTop: "Back to top ↑",
    madeIn: "Taught from Egypt · Trusted across MENA",
  },

  notFound: {
    kicker: "404",
    titleA: "This page didn't pass the",
    titleI: "checkpoint quiz",
    titleB: ".",
    sub: "The lesson you're looking for moved, graduated or never enrolled. Let's get you back on the path.",
    home: "Back home →",
    courses: "Browse courses",
  },
};

export const dict = { en };
