// ---- Bilingual UI dictionary (EN default · AR RTL) ---------------------------
// Course data (curricula, lessons) lives in lib/courses — tool vocabulary stays
// English by market convention; everything student-facing here is bilingual.

export type Lang = "en" | "ar";

const en = {
  nav: {
    courses: "Courses",
    bundle: "Bundle",
    instructor: "Instructor",
    blog: "Journal",
    faq: "FAQ",
    contact: "Contact",
    login: "Log in",
    logout: "Log out",
    dashboard: "My learning",
    startFree: "Start free ✦",
    allCourses: "All courses →",
    langBtn: "ع",
    roleTag: "· School of Visual Direction",
  },

  common: {
    enroll: "Enroll now ✦",
    enrollFree: "Start learning free ✦",
    continueLearning: "Continue learning",
    viewCourse: "View course",
    lessons: "lessons",
    lesson: "Lesson",
    hours: "hours",
    modules: "modules",
    projects: "projects",
    level: "Level",
    students: "students",
    graduates: "graduates",
    academies: "academies",
    certificate: "Verified certificate",
    free: "Free",
    premium: "Premium",
    save: "Save",
    enrolled: "Enrolled ✓",
    completed: "Completed",
    inProgress: "In progress",
    notStarted: "Not started",
    by: "by",
    back: "Back",
    close: "Close",
    comingSoon: "Coming soon",
    downloadPng: "Download PNG",
    minutesShort: "m",
    hoursShort: "h",
    freePreview: "Free preview",
    locked: "Locked",
    rating: "rating",
    reviewsWord: "reviews",
    of: "of",
    home: "Home",
  },

  home: {
    kicker: "Atelier — online school",
    heroA: "Design is a craft.",
    heroI: "Learn it",
    heroB: "like one.",
    heroSub:
      "Short, surgical courses — 3 to 5 hours each — that take you from zero to a professional workflow in Photoshop, Illustrator, After Effects, Premiere, Figma and AI production. Taught by a working art director, not a narrator.",
    ctaPrimary: "Start free ✦",
    ctaSecondary: "Browse courses",
    heroCardTag: "Free flagship course",
    marquee: ["Photoshop", "Illustrator", "After Effects", "Premiere Pro", "Figma", "AI Photoshoot", "AI Video", "Certificates", "Projects", "Zero → Pro"],
    statsLabel: "The record",
    stats: {
      graduates: "graduates taught",
      academies: "academies teach his method",
      hours: "hours of zero-filler curriculum",
      lessons: "hands-on lessons",
    },
    coursesLabel: "The catalog",
    coursesTitleA: "Seven tools.",
    coursesTitleI: "One standard",
    coursesTitleB: ".",
    coursesNote: "Every course: 3–5 hours, real projects, checkpoint quizzes, a final project and a verified certificate. No filler — ever.",
    pathLabel: "The method",
    pathTitleA: "Zero →",
    pathTitleI: "professional workflow",
    pathTitleB: ", by design.",
    pathNote: "The same arc in every course — the way ateliers have always taught craft.",
    path: [
      { t: "Learn", d: "Short lessons with a working file open. Watch, pause, do." },
      { t: "Practice", d: "Drills after every module — because tools become instinct through reps." },
      { t: "Project", d: "Real briefs, not exercises. You build portfolio pieces, not homework." },
      { t: "Checkpoint", d: "Quizzes that test decisions, not trivia. Pass them and you know you know." },
      { t: "Certificate", d: "Finish the final project and earn a verified certificate with your name on it." },
    ],
    whyLabel: "Why Atelier",
    whyTitleA: "Courses built like",
    whyTitleI: "campaigns",
    whyTitleB: ".",
    why: [
      { t: "A director, not a narrator", d: "Every lesson comes from live client work — campaigns, identities, films that shipped. You learn decisions, not buttons." },
      { t: "3–5 hours, zero filler", d: "Courses are edited like films. If a minute doesn't change how you work, it's cut." },
      { t: "Projects over playback", d: "Every module ends with your hands on a real brief. Finishing means a portfolio, not a watch history." },
      { t: "Arabic-friendly, world-standard", d: "Taught for the MENA market, benchmarked against global studio craft." },
    ],
    instructorLabel: "The instructor",
    instructorTitleA: "Taught by a working",
    instructorTitleI: "art director",
    instructorTitleB: ".",
    instructorBio:
      "Mohamed Tarek leads brand, campaign and motion work across Egypt, Saudi Arabia and Kuwait — and has taught 1,200+ students across four academies. Atelier is his method, distilled: the exact workflows his teams use on paying briefs.",
    instructorCta: "Meet the instructor",
    brandsNote: "Brands his work has served",
    bundleLabel: "Best value",
    bundleCta: "Get the bundle ✦",
    bundleNote: "vs. buying separately",
    testimonialsLabel: "Student words",
    testimonialsTitleA: "They came for a tool.",
    testimonialsTitleI: "They left with a craft",
    testimonialsTitleB: ".",
    faqLabel: "Questions",
    faqTitle: "Before you ask —",
    faqCta: "All questions answered",
    finalLabel: "Begin",
    finalTitleA: "Your first lesson is",
    finalTitleI: "free",
    finalTitleB: ". Your excuse isn't.",
    finalSub: "Start the AI Photoshoot course now — no card, no trial, no catch. Just the method, proven.",
    finalCta: "Start the free course ✦",
    finalAlt: "or browse all courses",
  },

  catalog: {
    metaTitle: "Courses — Photoshop, Illustrator, After Effects, Premiere, Figma & AI",
    kicker: "The catalog",
    titleA: "Choose your",
    titleI: "craft",
    titleB: ".",
    sub: "Seven focused courses. Each one: 3–5 hours, projects, quizzes, final project, certificate.",
    all: "All",
    filterDesign: "Design",
    filterMotion: "Motion & Video",
    filterAi: "AI Production",
    bundleCard: "The Ultimate Design Bundle",
    bundleCardSub: "Photoshop + AI Photoshoot + AI Video — one enrollment",
    empty: "No courses in this filter yet.",
  },

  course: {
    breadcrumbCourses: "Courses",
    heroIncludes: "This course includes",
    includesItems: [
      "Lifetime access, updates included",
      "Practical projects & working files",
      "Checkpoint quizzes",
      "Final project with certificate",
      "Downloadable resources",
      "WhatsApp support from the instructor",
    ],
    whatYouLearn: "What you walk out with",
    pathLabel: "Learning path",
    curriculumLabel: "Curriculum",
    curriculumNote: "Editorial index — every lesson, every minute, no padding.",
    projectsLabel: "Practical projects",
    resourcesLabel: "Downloadable resources",
    finalProjectLabel: "Final project",
    deliverables: "You deliver",
    certLabel: "Certificate",
    certTitle: "Finish it. Frame it.",
    certNote:
      "Complete every lesson, pass the checkpoint quiz and submit the final project — your verified Atelier certificate is issued with your name and a unique ID.",
    instructorLabel: "Your instructor",
    reviewsLabel: "Student reviews",
    faqLabel: "Course FAQ",
    enrollTitle: "Enroll in this course",
    bundleHint: "Part of the Ultimate Design Bundle —",
    bundleHintCta: "see the bundle",
    guarantee: "7-day money-back guarantee — no forms, one WhatsApp message.",
    startFreeNote: "Free forever. No card required.",
    alreadyEnrolled: "You're enrolled —",
    goToCourse: "go to the course →",
    audienceLabel: "Who it's for",
    toolsLabel: "Tools covered",
    relatedLabel: "Pairs well with",
  },

  bundle: {
    metaTitle: "The Ultimate Design Bundle — Photoshop + AI Photoshoot + AI Video",
    kicker: "The bundle",
    includes: "Three courses. One pipeline.",
    note: "The complete camera-less campaign stack — craft, generation and motion.",
    totalRuntime: "total runtime",
    totalLessons: "lessons",
    certNote: "3 verified certificates — one per course",
    cta: "Enroll in the bundle ✦",
    vs: "bought separately",
    save: "you save",
  },

  auth: {
    loginTitle: "Welcome back.",
    loginSub: "Your courses, progress and certificates are waiting.",
    registerTitle: "Start your craft.",
    registerSub: "One account — every course, project and certificate lives here.",
    name: "Full name",
    namePh: "e.g. Salma Ibrahim",
    email: "Email",
    emailPh: "you@example.com",
    password: "Password",
    passwordPh: "••••••••",
    loginBtn: "Log in →",
    registerBtn: "Create account →",
    orRegister: "New to Atelier?",
    orLogin: "Already have an account?",
    registerLink: "Create an account",
    loginLink: "Log in",
    demoNote: "Demo platform: your account lives in this browser only — no server, no spam, no password stored.",
    errName: "Please enter your name.",
    errEmail: "Please enter a valid email.",
  },

  checkout: {
    metaTitle: "Checkout",
    kicker: "Checkout",
    title: "Almost in.",
    orderLabel: "Your order",
    payLabel: "Payment method",
    instapay: "InstaPay",
    vodafone: "Vodafone Cash",
    manualNote:
      "Transfer the amount, then tap the button below — send your payment screenshot on WhatsApp and your access is activated personally, usually within minutes.",
    gatewaysSoon: "Card payments (Paymob · Fawry · valU) — arriving soon.",
    total: "Total",
    confirmBtn: "I've paid — confirm on WhatsApp ✦",
    freeBtn: "Enroll free — instant access ✦",
    backTo: "Back to course",
    secure: "Manual, human-verified enrollment — the same flow 1,200+ students used.",
    loginFirst: "Log in or create an account to complete enrollment.",
  },

  success: {
    enrollTitle: "You're in.",
    enrollSub: "Your enrollment is confirmed. Your first lesson is one click away — momentum matters, start now.",
    goDashboard: "Go to my learning →",
    startCourse: "Start the course ✦",
    certTitle: "Certificate earned.",
    certSub: "Your certificate has been issued with a unique ID. Download it, frame it, post it.",
    viewCert: "View my certificate →",
  },

  dash: {
    metaTitle: "My Learning",
    kicker: "Student dashboard",
    greetingM: "Good morning",
    greetingA: "Good afternoon",
    greetingE: "Good evening",
    subEmpty: "Your desk is clear. Pick a course and make it messy.",
    sub: "Pick up exactly where you left off.",
    continueLabel: "Continue",
    enrolledLabel: "My courses",
    progressWord: "complete",
    certsLabel: "Certificates",
    certsEmpty: "Finish a course to earn your first certificate.",
    browseCta: "Browse the catalog →",
    statsLessons: "lessons completed",
    statsMinutes: "minutes of craft",
    statsCerts: "certificates",
    quizReady: "Checkpoint quiz ready",
    finalStep: "Final step: pass the checkpoint quiz",
    claimCert: "Claim your certificate ✦",
  },

  learn: {
    curriculum: "Curriculum",
    nowPlaying: "Now playing",
    comingSoon: "Video — publishing soon",
    playerNote: "Lessons are being filmed and published module by module. Progress tracking, resources and quizzes are live now.",
    markDone: "Mark lesson complete",
    markedDone: "Completed ✓",
    next: "Next lesson →",
    prev: "← Previous",
    resources: "Resources",
    resourceGet: "Download",
    resourceLocked: "Enroll to download",
    quizTitle: "Checkpoint quiz",
    quizIntro: "Six decisions. Pass 5 to clear the checkpoint — this is where knowing becomes owning.",
    quizStart: "Start the quiz →",
    quizQuestion: "Question",
    quizCheck: "Check answers",
    quizPassed: "Checkpoint cleared ✓",
    quizFailed: "Not yet — review the misses and retry.",
    quizRetry: "Retry",
    quizScore: "Your score",
    progressLabel: "Course progress",
    backToDash: "← My learning",
    enrollGate: "Enroll to open the full course",
    enrollGateSub: "The first lessons are free previews — the rest unlocks with enrollment.",
    finalProjectTab: "Final project",
    overviewTab: "Overview",
  },

  profile: {
    metaTitle: "Profile",
    kicker: "Student profile",
    memberSince: "Learning since",
    editName: "Display name",
    saveBtn: "Save changes",
    saved: "Saved ✓",
    dangerLabel: "Session",
    logoutBtn: "Log out",
    resetBtn: "Reset all demo data",
    resetConfirm: "This clears your account, progress and certificates from this browser. Sure?",
    statsLabel: "Your numbers",
  },

  certs: {
    metaTitle: "Certificates",
    kicker: "The wall",
    title: "Certificates",
    sub: "Verified, uniquely numbered, and earned — never given.",
    empty: "No certificates yet. The first one changes everything.",
    emptyCta: "Find your course →",
    issuedTo: "Issued to",
    issuedOn: "Date",
    certNo: "Certificate ID",
    verify: "Verified by Atelier — School of Visual Direction",
  },

  downloads: {
    metaTitle: "Downloads",
    kicker: "The vault",
    title: "Downloads",
    sub: "Working files, cheat sheets and templates from your enrolled courses.",
    empty: "Enroll in a course to unlock its resource vault.",
    perCourse: "From",
  },

  blogUi: {
    metaTitle: "Journal — Design Education, Career Paths & AI Production",
    kicker: "The journal",
    titleA: "Notes from the",
    titleI: "atelier",
    titleB: ".",
    sub: "Honest writing on learning design, career sequencing and AI production — from the desk, not the content calendar.",
    readMore: "Read →",
    minsRead: "min read",
    relatedCourse: "The course behind this article",
    backToBlog: "← All articles",
    faqInPost: "Quick answers",
  },

  faqPage: {
    metaTitle: "FAQ — Enrollment, Certificates, Payments & Access",
    kicker: "Questions",
    titleA: "Everything you'd",
    titleI: "ask",
    titleB: ", answered.",
    sub: "Enrollment, payments, certificates, tools — if it's not here, WhatsApp me directly.",
    stillCta: "Still curious? Talk to me →",
    items: [
      { q: "How do courses work at Atelier?", a: "Every course is 3–5 hours of focused video organized into modules, with drills, real projects, downloadable working files, checkpoint quizzes and a final project. Finish everything and a verified certificate is issued with your name and a unique ID." },
      { q: "Why are the courses so short?", a: "Because they're edited like films. Ten-hour courses are ten hours because nobody cut them. Atelier courses keep only the minutes that change how you work — the rest of your time goes into practice, which is where skill actually forms." },
      { q: "How do I pay from Egypt?", a: "InstaPay or Vodafone Cash: transfer, send the screenshot on WhatsApp, and your access is activated personally — usually within minutes. Card gateways (Paymob, Fawry, valU) are arriving soon." },
      { q: "Is there really a free course?", a: "Yes — AI Photoshoot & Prompt Engineering, the complete 3-hour course, free forever with its certificate. It exists so you can judge the teaching before paying for anything." },
      { q: "Do I get lifetime access?", a: "Yes. One payment, permanent access, all future updates to that course included." },
      { q: "What if the course isn't for me?", a: "7-day money-back guarantee. One WhatsApp message, no forms, no questions that matter." },
      { q: "Are certificates recognized?", a: "Each certificate carries a unique verification ID and represents completed projects, passed quizzes and a submitted final project — a portfolio-backed credential, which is what employers actually check." },
      { q: "Do I need a powerful computer?", a: "No. Every course is taught on mid-range hardware, with performance workarounds (like Premiere proxies) built into the curriculum." },
      { q: "Is the teaching in Arabic or English?", a: "Lessons are taught in Arabic with English tool vocabulary — the way MENA studios actually talk. The platform itself is fully bilingual." },
      { q: "Can I get training for my team or academy?", a: "Yes — corporate and academy programs run separately (on-site in Egypt, online elsewhere). Reach out via the contact page and I'll reply personally." },
    ],
  },

  contact: {
    metaTitle: "Contact — Talk to the Instructor",
    kicker: "Contact",
    titleA: "Talk to a",
    titleI: "person",
    titleB: ". Me, specifically.",
    sub: "Enrollment help, team training, academy partnerships or just a question about your path — I answer personally, usually same-day.",
    waCta: "WhatsApp me →",
    emailCta: "Email me →",
    formName: "Your name",
    formEmail: "Your email",
    formTopic: "Topic",
    topics: ["Course question", "Enrollment / payment help", "Team or academy training", "Something else"],
    formMsg: "Your message",
    formSend: "Send message →",
    formNote: "Opens your email app with everything pre-filled.",
    trainingTitle: "Companies & academies",
    trainingNote: "Custom programs for teams — brand, campaign, motion and AI production. On-site in Egypt, online everywhere else.",
  },

  legal: {
    kicker: "Legal",
    updated: "Last updated",
    terms: {
      title: "Terms of Service",
      sections: [
        { h: "The service", p: "Atelier provides online design education: video lessons, projects, resources, quizzes and certificates. Access to paid courses is granted per person after payment confirmation and is not transferable or shareable." },
        { h: "Enrollment & access", p: "Paid enrollments grant lifetime access to the purchased course, including future updates to that course. Free courses may be updated, extended or restructured at any time." },
        { h: "Acceptable use", p: "Course videos, files and resources are licensed to you personally. Redistributing, reselling, screen-recording for sharing, or uploading materials elsewhere terminates access without refund and may carry legal consequences." },
        { h: "Certificates", p: "Certificates are issued upon genuine completion: all lessons, passed checkpoint quizzes and a submitted final project. Certificates carry unique IDs and misrepresentation of them is prohibited." },
        { h: "Refunds", p: "A 7-day money-back guarantee applies to paid courses — see the Refund Policy for the exact terms." },
        { h: "Changes", p: "These terms may be updated; continued use after changes constitutes acceptance. Material changes will be announced on the platform." },
      ],
    },
    privacy: {
      title: "Privacy Policy",
      sections: [
        { h: "What this demo stores", p: "This platform currently runs fully in your browser: your account name, email, course progress and certificates are stored in your browser's local storage only. No server receives, processes or sells this data." },
        { h: "Payments", p: "Payments run through InstaPay, Vodafone Cash or (soon) licensed gateways. Atelier never sees or stores card numbers; payment confirmation happens via WhatsApp screenshots you choose to send." },
        { h: "Communication", p: "WhatsApp and email conversations are used solely to activate access, provide support and — only with your consent — share course updates." },
        { h: "Analytics", p: "If analytics are enabled, they are aggregate and anonymous: page views and course popularity, never personal learning data tied to your identity." },
        { h: "Your rights", p: "You can clear all locally-stored data anytime from your Profile page, and request deletion of any support-conversation history via WhatsApp or email." },
      ],
    },
    refunds: {
      title: "Refund Policy",
      sections: [
        { h: "The guarantee", p: "Every paid course carries a 7-day money-back guarantee, counted from access activation. If it isn't right for you, one WhatsApp message gets your money back — no forms, no friction." },
        { h: "How refunds work", p: "Send your enrollment details on WhatsApp within 7 days. Refunds are returned via the same method you paid (InstaPay / Vodafone Cash) within 3 business days." },
        { h: "Fair use", p: "The guarantee exists to remove risk, not to lend content: accounts that complete more than 60% of a course or download its full resource vault before requesting a refund may be reviewed individually." },
        { h: "Bundles", p: "Bundle refunds work identically within the 7-day window. Partial bundle refunds (keeping one course) are handled personally — just ask." },
      ],
    },
  },

  footer: {
    blurb: "Atelier is the online school of art director Mohamed Tarek — short, premium design courses that end in real projects, real skills and verified certificates.",
    learnCol: "Learn",
    platformCol: "Platform",
    companyCol: "School",
    legalCol: "Legal",
    connectCol: "Connect",
    rights: "All rights reserved.",
    backTop: "Back to top ↑",
    madeIn: "Taught from Egypt · Trusted across MENA",
  },

  notFound: {
    kicker: "404",
    titleA: "This page didn't pass the",
    titleI: "checkpoint quiz",
    titleB: ".",
    sub: "The lesson you're looking for moved, graduated or never enrolled. Let's get you back on the path.",
    home: "Back home →",
    courses: "Browse courses",
  },
};

// ---------------------------------------------------------------- Arabic
const ar: typeof en = {
  nav: {
    courses: "الكورسات",
    bundle: "الباقة",
    instructor: "المدرّب",
    blog: "المدوّنة",
    faq: "الأسئلة",
    contact: "تواصل",
    login: "دخول",
    logout: "خروج",
    dashboard: "تعلّمي",
    startFree: "ابدأ مجانًا ✦",
    allCourses: "كل الكورسات ←",
    langBtn: "EN",
    roleTag: "· مدرسة الإخراج البصري",
  },

  common: {
    enroll: "اشترك الآن ✦",
    enrollFree: "ابدأ التعلّم مجانًا ✦",
    continueLearning: "كمّل تعلّمك",
    viewCourse: "شوف الكورس",
    lessons: "درس",
    lesson: "درس",
    hours: "ساعات",
    modules: "وحدات",
    projects: "مشاريع",
    level: "المستوى",
    students: "طالب",
    graduates: "خريج",
    academies: "أكاديميات",
    certificate: "شهادة موثّقة",
    free: "مجاني",
    premium: "مدفوع",
    save: "وفّر",
    enrolled: "مشترك ✓",
    completed: "مكتمل",
    inProgress: "مستمر",
    notStarted: "لم يبدأ",
    by: "بواسطة",
    back: "رجوع",
    close: "إغلاق",
    comingSoon: "قريبًا",
    downloadPng: "تحميل PNG",
    minutesShort: "د",
    hoursShort: "س",
    freePreview: "معاينة مجانية",
    locked: "مقفول",
    rating: "التقييم",
    reviewsWord: "تقييم",
    of: "من",
    home: "الرئيسية",
  },

  home: {
    kicker: "أتيلييه — مدرسة أونلاين",
    heroA: "التصميم حِرفة.",
    heroI: "اتعلمه",
    heroB: "كده.",
    heroSub:
      "كورسات قصيرة ومركّزة — من ٣ لـ ٥ ساعات — تاخدك من الصفر لـ Workflow احترافي في فوتوشوب وإليستريتور وأفتر إفكتس وبريمير وفيجما وإنتاج الذكاء الاصطناعي. بيدرّسها آرت دايركتور شغّال، مش معلّق صوتي.",
    ctaPrimary: "ابدأ مجانًا ✦",
    ctaSecondary: "تصفّح الكورسات",
    heroCardTag: "الكورس المجاني الأساسي",
    marquee: ["فوتوشوب", "إليستريتور", "أفتر إفكتس", "بريمير برو", "فيجما", "تصوير AI", "فيديو AI", "شهادات", "مشاريع", "من الصفر للاحتراف"],
    statsLabel: "السجل",
    stats: {
      graduates: "طالب اتعلموا معاه",
      academies: "أكاديميات بتدرّس بطريقته",
      hours: "ساعات منهج من غير حشو",
      lessons: "درس عملي",
    },
    coursesLabel: "الكتالوج",
    coursesTitleA: "سبع أدوات.",
    coursesTitleI: "معيار واحد",
    coursesTitleB: ".",
    coursesNote: "كل كورس: ٣–٥ ساعات، مشاريع حقيقية، اختبارات، مشروع نهائي وشهادة موثّقة. من غير حشو — أبدًا.",
    pathLabel: "المنهج",
    pathTitleA: "من الصفر ←",
    pathTitleI: "لـ Workflow احترافي",
    pathTitleB: "، بالتصميم.",
    pathNote: "نفس المسار في كل كورس — زي ما الورش بتعلّم الحِرفة من زمان.",
    path: [
      { t: "اتعلم", d: "دروس قصيرة وملف الشغل مفتوح. اتفرج، وقّف، نفّذ." },
      { t: "اتمرّن", d: "تمارين بعد كل وحدة — لأن الأدوات بتبقى غريزة بالتكرار." },
      { t: "مشروع", d: "بريفات حقيقية مش تمارين. بتبني شغل يدخل البورتفوليو، مش واجبات." },
      { t: "اختبار", d: "أسئلة بتختبر القرارات مش المعلومات. لما تعدّيها تبقى متأكد إنك فاهم." },
      { t: "شهادة", d: "خلّص المشروع النهائي واستلم شهادة موثّقة باسمك." },
    ],
    whyLabel: "ليه أتيلييه",
    whyTitleA: "كورسات متبنية زي",
    whyTitleI: "الحملات",
    whyTitleB: ".",
    why: [
      { t: "مخرج مش معلّق صوتي", d: "كل درس طالع من شغل حقيقي مع عملاء — حملات وهويات وأفلام اتسلّمت فعلًا. بتتعلم القرارات مش الأزرار." },
      { t: "٣–٥ ساعات، صفر حشو", d: "الكورسات متمنتجة زي الأفلام. أي دقيقة مش هتغيّر طريقة شغلك — بتتشال." },
      { t: "مشاريع مش مشاهدة", d: "كل وحدة بتخلص وإيدك في بريف حقيقي. الإنهاء معناه بورتفوليو، مش سجل مشاهدة." },
      { t: "بالعربي، وبمعايير عالمية", d: "متدرّس لسوق الشرق الأوسط، ومتقاس على مستوى الاستوديوهات العالمية." },
    ],
    instructorLabel: "المدرّب",
    instructorTitleA: "بيدرّسه",
    instructorTitleI: "آرت دايركتور شغّال",
    instructorTitleB: ".",
    instructorBio:
      "محمد طارق بيقود شغل برندات وحملات وموشن في مصر والسعودية والكويت — ودرّس لأكتر من ١٢٠٠ طالب في أربع أكاديميات. أتيلييه هي طريقته مركّزة: نفس الـ Workflows اللي فرقه بتستخدمها في شغل مدفوع.",
    instructorCta: "اعرف المدرّب",
    brandsNote: "براندات خدمها شغله",
    bundleLabel: "أفضل قيمة",
    bundleCta: "احصل على الباقة ✦",
    bundleNote: "مقارنة بالشراء المنفصل",
    testimonialsLabel: "كلام الطلبة",
    testimonialsTitleA: "جُم علشان أداة.",
    testimonialsTitleI: "خرجوا بحِرفة",
    testimonialsTitleB: ".",
    faqLabel: "أسئلة",
    faqTitle: "قبل ما تسأل —",
    faqCta: "كل الأسئلة والإجابات",
    finalLabel: "ابدأ",
    finalTitleA: "أول درس ليك",
    finalTitleI: "مجاني",
    finalTitleB: ". وعذرك مش مجاني.",
    finalSub: "ابدأ كورس التصوير بالذكاء الاصطناعي دلوقتي — من غير كارت، من غير تجربة، من غير لعب. المنهج نفسه، مُثبت.",
    finalCta: "ابدأ الكورس المجاني ✦",
    finalAlt: "أو تصفّح كل الكورسات",
  },

  catalog: {
    metaTitle: "الكورسات — فوتوشوب وإليستريتور وأفتر إفكتس وبريمير وفيجما وAI",
    kicker: "الكتالوج",
    titleA: "اختار",
    titleI: "حِرفتك",
    titleB: ".",
    sub: "سبع كورسات مركّزة. كل واحد: ٣–٥ ساعات، مشاريع، اختبارات، مشروع نهائي وشهادة.",
    all: "الكل",
    filterDesign: "تصميم",
    filterMotion: "موشن وفيديو",
    filterAi: "إنتاج AI",
    bundleCard: "باقة التصميم الشاملة",
    bundleCardSub: "فوتوشوب + تصوير AI + فيديو AI — باشتراك واحد",
    empty: "مفيش كورسات في الفلتر ده حاليًا.",
  },

  course: {
    breadcrumbCourses: "الكورسات",
    heroIncludes: "الكورس ده بيشمل",
    includesItems: [
      "وصول مدى الحياة مع التحديثات",
      "مشاريع عملية وملفات شغل",
      "اختبارات بعد الوحدات",
      "مشروع نهائي بشهادة",
      "ملفات ومصادر للتحميل",
      "دعم واتساب من المدرّب شخصيًا",
    ],
    whatYouLearn: "هتخرج بإيه",
    pathLabel: "مسار التعلّم",
    curriculumLabel: "المنهج",
    curriculumNote: "فهرس تحريري — كل درس، كل دقيقة، من غير حشو.",
    projectsLabel: "المشاريع العملية",
    resourcesLabel: "ملفات للتحميل",
    finalProjectLabel: "المشروع النهائي",
    deliverables: "هتسلّم",
    certLabel: "الشهادة",
    certTitle: "خلّصه. علّقه.",
    certNote:
      "خلّص كل الدروس، اعدّي الاختبار، وسلّم المشروع النهائي — وشهادة أتيلييه الموثّقة بتتصدر باسمك برقم فريد.",
    instructorLabel: "مدرّبك",
    reviewsLabel: "تقييمات الطلبة",
    faqLabel: "أسئلة الكورس",
    enrollTitle: "اشترك في الكورس",
    bundleHint: "جزء من باقة التصميم الشاملة —",
    bundleHintCta: "شوف الباقة",
    guarantee: "ضمان استرجاع الفلوس ٧ أيام — من غير استمارات، رسالة واتساب واحدة.",
    startFreeNote: "مجاني للأبد. من غير كارت.",
    alreadyEnrolled: "إنت مشترك —",
    goToCourse: "ادخل الكورس ←",
    audienceLabel: "لمين الكورس ده",
    toolsLabel: "الأدوات",
    relatedLabel: "بيكمّل بعضه مع",
  },

  bundle: {
    metaTitle: "باقة التصميم الشاملة — فوتوشوب + تصوير AI + فيديو AI",
    kicker: "الباقة",
    includes: "تلات كورسات. خط إنتاج واحد.",
    note: "منظومة الحملات الكاملة من غير كاميرا — حِرفة وتوليد وموشن.",
    totalRuntime: "إجمالي المدة",
    totalLessons: "درس",
    certNote: "٣ شهادات موثّقة — شهادة لكل كورس",
    cta: "اشترك في الباقة ✦",
    vs: "لو اشتريتهم منفصلين",
    save: "بتوفّر",
  },

  auth: {
    loginTitle: "أهلًا بعودتك.",
    loginSub: "كورساتك وتقدّمك وشهاداتك مستنيينك.",
    registerTitle: "ابدأ حِرفتك.",
    registerSub: "حساب واحد — كل كورس ومشروع وشهادة بيعيشوا هنا.",
    name: "الاسم الكامل",
    namePh: "مثال: سلمى إبراهيم",
    email: "الإيميل",
    emailPh: "you@example.com",
    password: "كلمة السر",
    passwordPh: "••••••••",
    loginBtn: "دخول ←",
    registerBtn: "إنشاء حساب ←",
    orRegister: "جديد على أتيلييه؟",
    orLogin: "عندك حساب بالفعل؟",
    registerLink: "اعمل حساب",
    loginLink: "سجّل دخول",
    demoNote: "منصة تجريبية: حسابك بيعيش في المتصفح ده بس — من غير سيرفر، من غير سبام، ومن غير تخزين كلمة سر.",
    errName: "من فضلك اكتب اسمك.",
    errEmail: "من فضلك اكتب إيميل صحيح.",
  },

  checkout: {
    metaTitle: "إتمام الاشتراك",
    kicker: "الدفع",
    title: "قرّبت توصل.",
    orderLabel: "طلبك",
    payLabel: "طريقة الدفع",
    instapay: "إنستاباي",
    vodafone: "فودافون كاش",
    manualNote:
      "حوّل المبلغ وبعدين دوس الزرار اللي تحت — ابعت سكرين الدفع على واتساب وهفعّل اشتراكك بنفسي، غالبًا في دقايق.",
    gatewaysSoon: "الدفع بالكارت (باي موب · فوري · فاليو) — قريبًا.",
    total: "الإجمالي",
    confirmBtn: "دفعت — أكّد على واتساب ✦",
    freeBtn: "اشترك مجانًا — وصول فوري ✦",
    backTo: "رجوع للكورس",
    secure: "اشتراك يدوي متحقق منه إنسانيًا — نفس الطريقة اللي استخدمها +١٢٠٠ طالب.",
    loginFirst: "سجّل دخول أو اعمل حساب علشان تكمّل الاشتراك.",
  },

  success: {
    enrollTitle: "دخلت.",
    enrollSub: "اشتراكك اتأكد. أول درس على بُعد ضغطة — الزخم مهم، ابدأ دلوقتي.",
    goDashboard: "روح لتعلّمي ←",
    startCourse: "ابدأ الكورس ✦",
    certTitle: "الشهادة اتصدرت.",
    certSub: "شهادتك اتصدرت برقم فريد. حمّلها، علّقها، انشرها.",
    viewCert: "شوف شهادتي ←",
  },

  dash: {
    metaTitle: "تعلّمي",
    kicker: "لوحة الطالب",
    greetingM: "صباح الخير",
    greetingA: "مساء الخير",
    greetingE: "مساء الخير",
    subEmpty: "مكتبك فاضي. اختار كورس وابدأ شغل.",
    sub: "كمّل من نفس النقطة اللي وقفت عندها بالظبط.",
    continueLabel: "كمّل",
    enrolledLabel: "كورساتي",
    progressWord: "مكتمل",
    certsLabel: "الشهادات",
    certsEmpty: "خلّص كورس علشان تاخد أول شهادة.",
    browseCta: "تصفّح الكتالوج ←",
    statsLessons: "درس مكتمل",
    statsMinutes: "دقيقة حِرفة",
    statsCerts: "شهادات",
    quizReady: "اختبار الوحدة جاهز",
    finalStep: "الخطوة الأخيرة: اعدّي الاختبار",
    claimCert: "استلم شهادتك ✦",
  },

  learn: {
    curriculum: "المنهج",
    nowPlaying: "بيتشغّل الآن",
    comingSoon: "الفيديو — قريبًا",
    playerNote: "الدروس بتتصور وتتنشر وحدة وحدة. تتبع التقدم والملفات والاختبارات شغالين دلوقتي.",
    markDone: "علّم الدرس كمكتمل",
    markedDone: "مكتمل ✓",
    next: "الدرس التالي ←",
    prev: "→ السابق",
    resources: "الملفات",
    resourceGet: "تحميل",
    resourceLocked: "اشترك علشان تحمّل",
    quizTitle: "اختبار الوحدة",
    quizIntro: "ست قرارات. عدّي ٥ علشان تفتح الشهادة — هنا المعرفة بتبقى امتلاك.",
    quizStart: "ابدأ الاختبار ←",
    quizQuestion: "سؤال",
    quizCheck: "صحّح الإجابات",
    quizPassed: "الاختبار اتعدّى ✓",
    quizFailed: "لسه — راجع الأخطاء وحاول تاني.",
    quizRetry: "حاول تاني",
    quizScore: "نتيجتك",
    progressLabel: "تقدّم الكورس",
    backToDash: "→ تعلّمي",
    enrollGate: "اشترك علشان تفتح الكورس كامل",
    enrollGateSub: "أول دروس معاينة مجانية — الباقي بيتفتح بالاشتراك.",
    finalProjectTab: "المشروع النهائي",
    overviewTab: "نظرة عامة",
  },

  profile: {
    metaTitle: "الملف الشخصي",
    kicker: "ملف الطالب",
    memberSince: "بيتعلم من",
    editName: "اسم العرض",
    saveBtn: "احفظ التغييرات",
    saved: "اتحفظ ✓",
    dangerLabel: "الجلسة",
    logoutBtn: "تسجيل خروج",
    resetBtn: "مسح كل بيانات التجربة",
    resetConfirm: "ده هيمسح حسابك وتقدمك وشهاداتك من المتصفح ده. متأكد؟",
    statsLabel: "أرقامك",
  },

  certs: {
    metaTitle: "الشهادات",
    kicker: "الحيطة",
    title: "الشهادات",
    sub: "موثّقة، بأرقام فريدة، ومُكتسبة — مش بتتوهب.",
    empty: "مفيش شهادات لسه. أول واحدة بتغيّر كل حاجة.",
    emptyCta: "دوّر على كورسك ←",
    issuedTo: "صادرة لـ",
    issuedOn: "التاريخ",
    certNo: "رقم الشهادة",
    verify: "موثّقة من أتيلييه — مدرسة الإخراج البصري",
  },

  downloads: {
    metaTitle: "التحميلات",
    kicker: "الخزنة",
    title: "التحميلات",
    sub: "ملفات شغل وشيتات وقوالب من كورساتك المشترك فيها.",
    empty: "اشترك في كورس علشان تفتح خزنة ملفاته.",
    perCourse: "من",
  },

  blogUi: {
    metaTitle: "المدوّنة — تعليم التصميم والمسارات المهنية وإنتاج AI",
    kicker: "المدوّنة",
    titleA: "ملاحظات من",
    titleI: "الأتيلييه",
    titleB: ".",
    sub: "كتابة صريحة عن تعلّم التصميم وترتيب المسار المهني وإنتاج الذكاء الاصطناعي — من المكتب، مش من جدول المحتوى.",
    readMore: "اقرأ ←",
    minsRead: "دقايق قراءة",
    relatedCourse: "الكورس ورا المقال ده",
    backToBlog: "→ كل المقالات",
    faqInPost: "إجابات سريعة",
  },

  faqPage: {
    metaTitle: "الأسئلة الشائعة — الاشتراك والشهادات والدفع والوصول",
    kicker: "أسئلة",
    titleA: "كل اللي ممكن",
    titleI: "تسأله",
    titleB: "، مُجاب.",
    sub: "الاشتراك، الدفع، الشهادات، الأدوات — لو مش هنا، ابعتلي واتساب مباشرة.",
    stillCta: "لسه عندك سؤال؟ كلّمني ←",
    items: [
      { q: "الكورسات بتشتغل إزاي في أتيلييه؟", a: "كل كورس ٣–٥ ساعات فيديو مركّز متقسم لوحدات، مع تمارين ومشاريع حقيقية وملفات شغل واختبارات ومشروع نهائي. خلّص كل حاجة وهتتصدر شهادة موثّقة باسمك برقم فريد." },
      { q: "ليه الكورسات قصيرة كده؟", a: "لأنها متمنتجة زي الأفلام. كورسات العشر ساعات عشر ساعات لأن محدش قصّها. كورسات أتيلييه بتحتفظ بس بالدقايق اللي بتغيّر طريقة شغلك — وباقي وقتك بيروح للتمرين، وهو المكان اللي المهارة بتتكوّن فيه فعلًا." },
      { q: "أدفع إزاي من مصر؟", a: "إنستاباي أو فودافون كاش: حوّل، ابعت السكرين على واتساب، وهفعّل اشتراكك بنفسي — غالبًا في دقايق. بوابات الكروت (باي موب، فوري، فاليو) جاية قريب." },
      { q: "في كورس مجاني بجد؟", a: "أيوه — التصوير بالذكاء الاصطناعي وهندسة البرومبت، كورس كامل ٣ ساعات، مجاني للأبد بشهادته. موجود علشان تحكم على التدريس قبل ما تدفع أي حاجة." },
      { q: "الوصول مدى الحياة؟", a: "أيوه. دفعة واحدة، وصول دائم، وكل تحديثات الكورس المستقبلية متضمنة." },
      { q: "ولو الكورس مش مناسب ليا؟", a: "ضمان استرجاع ٧ أيام. رسالة واتساب واحدة، من غير استمارات ولا أسئلة." },
      { q: "الشهادات معترف بيها؟", a: "كل شهادة ليها رقم تحقق فريد وبتمثل مشاريع مكتملة واختبارات متعدّية ومشروع نهائي متسلّم — شهادة مدعومة ببورتفوليو، وده اللي أصحاب الشغل بيبصوا عليه فعلًا." },
      { q: "محتاج جهاز قوي؟", a: "لأ. كل الكورسات متدرّسة على أجهزة متوسطة، مع حلول للأداء (زي البروكسي في بريمير) جوه المنهج نفسه." },
      { q: "التدريس بالعربي ولا بالإنجليزي؟", a: "الدروس بالعربي مع مصطلحات الأدوات بالإنجليزي — زي ما استوديوهات المنطقة بتتكلم فعلًا. المنصة نفسها ثنائية اللغة بالكامل." },
      { q: "ممكن تدريب لفريقي أو أكاديميتي؟", a: "أيوه — برامج الشركات والأكاديميات بتشتغل منفصل (حضوري في مصر، أونلاين خارجها). ابعتلي من صفحة التواصل وهرد بنفسي." },
    ],
  },

  contact: {
    metaTitle: "تواصل — اتكلم مع المدرّب",
    kicker: "تواصل",
    titleA: "اتكلم مع",
    titleI: "إنسان",
    titleB: ". أنا تحديدًا.",
    sub: "مساعدة في الاشتراك، تدريب فرق، شراكات أكاديميات أو حتى سؤال عن مسارك — برد بنفسي، غالبًا في نفس اليوم.",
    waCta: "واتساب ←",
    emailCta: "إيميل ←",
    formName: "اسمك",
    formEmail: "إيميلك",
    formTopic: "الموضوع",
    topics: ["سؤال عن كورس", "مساعدة في الاشتراك / الدفع", "تدريب فريق أو أكاديمية", "حاجة تانية"],
    formMsg: "رسالتك",
    formSend: "ابعت الرسالة ←",
    formNote: "بيفتح تطبيق الإيميل عندك وكل حاجة متجهزة.",
    trainingTitle: "الشركات والأكاديميات",
    trainingNote: "برامج مخصصة للفرق — برندات وحملات وموشن وإنتاج AI. حضوري في مصر، وأونلاين في أي مكان تاني.",
  },

  legal: {
    kicker: "قانوني",
    updated: "آخر تحديث",
    terms: {
      title: "شروط الاستخدام",
      sections: [
        { h: "الخدمة", p: "أتيلييه بتقدم تعليم تصميم أونلاين: دروس فيديو ومشاريع وملفات واختبارات وشهادات. الوصول للكورسات المدفوعة بيتمنح للشخص بعد تأكيد الدفع وغير قابل للنقل أو المشاركة." },
        { h: "الاشتراك والوصول", p: "الاشتراكات المدفوعة بتمنح وصول مدى الحياة للكورس المشترى، شامل تحديثاته المستقبلية. الكورسات المجانية ممكن تتحدث أو تتوسع أو يعاد هيكلتها في أي وقت." },
        { h: "الاستخدام المقبول", p: "فيديوهات الكورس وملفاته مرخصة ليك شخصيًا. إعادة التوزيع أو البيع أو تسجيل الشاشة للمشاركة أو رفع المواد في أي مكان تاني بينهي الوصول من غير استرجاع وقد يترتب عليه مسؤولية قانونية." },
        { h: "الشهادات", p: "الشهادات بتتصدر عند الإكمال الحقيقي: كل الدروس، اختبارات متعدّية، ومشروع نهائي متسلّم. الشهادات بأرقام فريدة وانتحالها ممنوع." },
        { h: "الاسترجاع", p: "ضمان استرجاع ٧ أيام بينطبق على الكورسات المدفوعة — راجع سياسة الاسترجاع للتفاصيل." },
        { h: "التغييرات", p: "الشروط دي ممكن تتحدث؛ استمرار الاستخدام بعد التغيير يعتبر موافقة. التغييرات الجوهرية هيتم الإعلان عنها على المنصة." },
      ],
    },
    privacy: {
      title: "سياسة الخصوصية",
      sections: [
        { h: "إيه اللي بيتخزن في النسخة دي", p: "المنصة حاليًا شغالة بالكامل في متصفحك: اسمك وإيميلك وتقدمك وشهاداتك متخزنين في التخزين المحلي لمتصفحك بس. مفيش سيرفر بيستقبل أو يعالج أو يبيع البيانات دي." },
        { h: "المدفوعات", p: "المدفوعات بتتم عبر إنستاباي أو فودافون كاش أو (قريبًا) بوابات مرخصة. أتيلييه عمرها ما بتشوف أو تخزن أرقام كروت؛ تأكيد الدفع بيتم عبر سكرينات واتساب إنت اللي بتختار تبعتها." },
        { h: "التواصل", p: "محادثات الواتساب والإيميل بتُستخدم فقط لتفعيل الوصول والدعم — وبموافقتك بس — لمشاركة تحديثات الكورسات." },
        { h: "التحليلات", p: "لو التحليلات مفعّلة فهي مجمّعة ومجهولة: مشاهدات صفحات وشعبية كورسات، مش بيانات تعلم شخصية مرتبطة بهويتك." },
        { h: "حقوقك", p: "تقدر تمسح كل البيانات المخزنة محليًا في أي وقت من صفحة الملف الشخصي، وتطلب حذف أي سجل محادثات دعم عبر واتساب أو الإيميل." },
      ],
    },
    refunds: {
      title: "سياسة الاسترجاع",
      sections: [
        { h: "الضمان", p: "كل كورس مدفوع عليه ضمان استرجاع ٧ أيام من تفعيل الوصول. لو مش مناسب ليك، رسالة واتساب واحدة بترجّع فلوسك — من غير استمارات ولا تعقيد." },
        { h: "الاسترجاع بيتم إزاي", p: "ابعت تفاصيل اشتراكك على واتساب خلال ٧ أيام. الفلوس بترجع بنفس طريقة الدفع (إنستاباي / فودافون كاش) خلال ٣ أيام عمل." },
        { h: "الاستخدام العادل", p: "الضمان موجود علشان يشيل المخاطرة، مش علشان إعارة المحتوى: الحسابات اللي كمّلت أكتر من ٦٠٪ من الكورس أو حمّلت كل ملفاته قبل طلب الاسترجاع ممكن تتراجع فرديًا." },
        { h: "الباقات", p: "استرجاع الباقات بنفس الطريقة خلال الـ ٧ أيام. الاسترجاع الجزئي (الاحتفاظ بكورس واحد) بيتظبط شخصيًا — اسأل بس." },
      ],
    },
  },

  footer: {
    blurb: "أتيلييه هي المدرسة الأونلاين للآرت دايركتور محمد طارق — كورسات تصميم قصيرة وبريميوم بتنتهي بمشاريع حقيقية ومهارات حقيقية وشهادات موثّقة.",
    learnCol: "اتعلم",
    platformCol: "المنصة",
    companyCol: "المدرسة",
    legalCol: "قانوني",
    connectCol: "تواصل",
    rights: "كل الحقوق محفوظة.",
    backTop: "فوق ↑",
    madeIn: "بيتدرّس من مصر · موثوق في الشرق الأوسط",
  },

  notFound: {
    kicker: "404",
    titleA: "الصفحة دي معدّتش",
    titleI: "اختبار الوحدة",
    titleB: ".",
    sub: "الدرس اللي بتدور عليه اتنقل أو اتخرّج أو أصلًا ما اشتركش. تعالَ نرجّعك للمسار.",
    home: "الرئيسية ←",
    courses: "تصفّح الكورسات",
  },
};

export const dict = { en, ar };
