// ---- UI dictionary (bilingual EN / AR-Fusha) ----------------------------------
// Course data (curricula, lessons) lives in lib/courses and carries its own
// Bi {en, ar} fields. Student reviews/feedback intentionally stay in their
// original language. `ar` is typed against `en` so a missing key fails the build.

export type Lang = "en" | "ar";

const en = {
  nav: {
    courses: "Courses",
    bundle: "Bundle",
    instructor: "Instructor",
    blog: "Blog",
    faq: "FAQ",
    contact: "Contact",
    login: "Log in",
    logout: "Log out",
    dashboard: "My learning",
    account: "Account settings",
    studio: "Studio",
    offers: "Offers",
    startFree: "Start free ✦",
    allCourses: "All courses →",
    training: "Agencies",
    roleTag: "· Visual Direction & AI Workflow",
  },

  promo: {
    tag: "Launch offers · end soon",
    codeLabel: "Your personal code",
    codeHint: "scratch to reveal · extra 5% at checkout",
    cta: "Claim this offer →",
    dismiss: "Maybe later",
    seeAll: "See all offers",
    shuffleHint: "Tap the deck for the next offer",
    cardOf: "of",
  },

  offersPage: {
    metaTitle: "Offers — Course Bundles & Launch Deals",
    kicker: "The offers",
    titleA: "Pick your",
    titleI: "plan",
    titleB: ".",
    sub: "Three packs side by side — each priced under the sum of its parts, each earning itself back on your first paid brief.",
    includes: "Inside this pack",
    runtime: "total runtime",
    lessonsWord: "lessons",
    save: "You save",
    cta: "Grab this pack ✦",
    best: "Best value",
    codeNote: "Have a promo code? It applies at checkout.",
    perOnce: "one payment · lifetime access",
    compareLabel: "What's inside, side by side",
    featCourses: "Courses included",
    featHours: "Hours of curriculum",
    featProjects: "Reviewed final projects",
    featAE: "After Effects — motion",
    featPr: "Premiere Pro — editing",
    featAiPhoto: "AI Photoshoot & prompts",
    featAiVideo: "AI Video generation",
    featSupport: "WhatsApp support",
    featLifetime: "Lifetime updates",
    tierEditors: "The editor's lane",
    tierStack: "The AI money lane",
    tierMaster: "Everything. All of it.",
  },

  promptFixer: {
    kicker: "Free track · Let's fix",
    titleA: "Paste any prompt.",
    titleI: "Watch it get fixed",
    titleB: ".",
    sub: "The same checklist I run on every client generation — free. Paste your prompt and see what a director adds.",
    placeholder: "e.g. a photo of a perfume bottle on a table…",
    fixBtn: "Fix my prompt ✦",
    fixedLabel: "The directed version",
    tipsLabel: "What was missing",
    copyBtn: "Copy",
    copied: "Copied ✓",
    emptyTip: "Write a prompt first — even one line.",
    tooShort: "Too short to direct. Describe the shot in at least 8 words — subject, setting and mood — and I'll take it from there.",
    grammarTip: "Grammar & spelling tidied so the model reads it cleanly.",
    humanTitle: "Who's in the frame?",
    humanNote: "There's a person in this prompt. Models drift to generic faces — nationality, age and place lock the casting.",
    natLabel: "Nationality",
    natPh: "e.g. Egyptian",
    ageLabel: "Age",
    agePh: "e.g. 27",
    placeLabel: "Where",
    placePh: "e.g. a sunlit Cairo apartment",
    humanApply: "Add & direct ✦",
    tips: {
      lens: "No lens. Focal length is how you direct perspective — 85mm flatters products and people, 35mm gives context.",
      light: "No light direction. Light is the photograph — name its quality and side: 'soft window light from camera left'.",
      comp: "No composition. Tell the frame where to breathe: negative space for the headline, rule-of-thirds placement.",
      palette: "No color world. A named palette ('warm amber, muted') keeps a whole campaign consistent.",
      constraints: "No constraints. 'No text, no logos, shallow depth of field' is what stops generic stock-photo drift.",
      subject: "Lead with a concrete subject and scene — the model can't guess what matters.",
      human: "Casting locked: nationality, age and place added — that's what stops generic AI faces.",
    },
    upsell: "That checklist, applied shot after shot until it's instinct — that's the whole course.",
  },

  offer: {
    text: "Launch offer — the AI Production Stack for EGP 3,950 instead of 5,000",
    ends: "Offer ends in",
    cta: "Grab it",
    days: "d",
    hours: "h",
    mins: "m",
    secs: "s",
  },

  common: {
    enroll: "Enroll now ✦",
    enrollFree: "Start learning free ✦",
    continueLearning: "Continue learning",
    viewCourse: "View course",
    lessons: "lessons",
    lesson: "Lesson",
    hours: "hours",
    modules: "modules",
    projects: "projects",
    level: "Level",
    students: "students",
    graduates: "graduates",
    academies: "academies",
    free: "Free",
    premium: "Premium",
    save: "Save",
    enrolled: "Enrolled ✓",
    completed: "Completed",
    inProgress: "In progress",
    notStarted: "Not started",
    by: "by",
    back: "Back",
    close: "Close",
    comingSoon: "Coming soon",
    downloadPng: "Download PNG",
    minutesShort: "m",
    hoursShort: "h",
    freePreview: "Free preview",
    locked: "Locked",
    rating: "rating",
    reviewsWord: "reviews",
    of: "of",
    home: "Home",
  },

  home: {
    kicker: "Mohamed Tarek — not another course site",
    heroA: "Own the craft.",
    heroI: "Out-design",
    heroB: "everyone.",
    heroSub:
      "Photoshop and Illustrator — free, complete, forever. After Effects, Premiere and the AI tracks cost a symbolic fraction of what a single freelance job pays. Learn the skill this week, earn it back on brief #1.",
    ctaPrimary: "Start free ✦",
    ctaSecondary: "Browse courses",
    heroCardTag: "Free — full course",
    heroStickers: ["2 free to start", "priced vs one freelance job", "zero filler"],
    scroll: "scroll",
    marquee: ["Photoshop — free", "Illustrator — free", "After Effects — pro", "Premiere Pro — pro", "AI Photoshoot — premium", "AI Video — premium", "Earn it back on brief #1", "No filler", "Zero → Pro"],
    statsLabel: "The record",
    stats: {
      graduates: "graduates taught",
      academies: "academies teach his method",
      hours: "hours of zero-filler curriculum",
      lessons: "hands-on lessons",
    },
    manLabel: "The deal",
    freeTitle: "Start free. Photoshop & Illustrator, in full.",
    freeBody: "The two foundations — complete courses with projects, quizzes and reviewed final projects, at EGP 0. Learn the craft everything else builds on. No card, no catch.",
    freeTag: "EGP 0 — forever",
    paidTitle: "The AI tracks — priced against one freelance job.",
    paidBody: "AI Photoshoot and AI Video are what clients pay serious budgets for right now. Each course costs a symbolic fraction of what a single AI brief pays — finish this week, earn it back on your first paid job.",
    paidTag: "Earn it back on brief #1",
    coursesLabel: "The software craft",
    coursesTitleA: "Master the",
    coursesTitleI: "tools",
    coursesTitleB: ".",
    coursesNote: "Photoshop & Illustrator free forever · After Effects & Premiere pro-priced — all complete, with projects, quizzes and a reviewed final project.",
    featuredLabel: "Premium · AI Photoshoot",
    featuredNote: "If you're here to earn, start here.",
    featuredVideoLabel: "Premium · AI Video",
    featuredVideoNote: "No camera. No crew. Broadcast-ready.",
    featuredCta: "Open the course ✦",
    featuredBrowse: "Browse everything",
    econLabel: "The economics",
    econTitleA: "Priced against one",
    econTitleI: "freelance job",
    econTitleB: ", not one course.",
    econ: [
      { n: "8,000+", u: "EGP", l: "what one freelance motion, edit or AI brief pays — routinely more" },
      { n: "1,050", u: "EGP", l: "the complete Premiere Pro course — once, forever" },
      { n: "brief #1", u: "", l: "pays the course back. Everything after that is profit." },
    ],
    storyLabel: "Featured story",
    storyQuote:
      "I finished the AI stack on a Friday. Two weeks later I quoted my first spot for more than my monthly salary — and the client didn't blink. The pricing lesson alone paid for everything.",
    storyName: "Khaled Emad",
    storyRole: "Freelance designer → AI production",
    storyChips: ["First paid brief: 3 weeks", "Now freelancing full-time", "AI Production Stack graduate"],
    giftTag: "A gift for your career",
    giftHint: "Tap to unwrap ✦",
    outcomesLabel: "Proof",
    outcomesTitleA: "Outcomes,",
    outcomesTitleI: "not promises",
    outcomesTitleB: ".",
    outcomes: [
      { n: 1200, s: "+", l: "students taught across four academies" },
      { n: 78, s: "%", l: "of finishers land paid work within 3 months" },
      { n: 21, s: "", l: "days on average to a first paid brief after the AI stack" },
      { n: 96, s: "%", l: "completion rate — 3–5 hour courses actually get finished" },
    ],
    galleryLabel: "Made with the method",
    communityNote:
      "Every student joins the private WhatsApp room — critiques, gigs and new drops land there first.",
    trustChips: ["Personal WhatsApp support", "Lifetime access", "Taught in Arabic"],
    instructorChipsLabel: "Industries his work has served",
    instructorChips: ["Automotive", "Real estate", "Medical", "F&B & hospitality", "Fashion & retail", "E-commerce", "Cinema & film", "Sports", "Food-tech", "Education"],
    pathLabel: "The method",
    pathTitleA: "Zero →",
    pathTitleI: "pro",
    pathTitleB: ", in five beats.",
    pathNote: "Every course, same arc.",
    path: [
      { t: "Learn", d: "Working file open. Watch, pause, do." },
      { t: "Practice", d: "Drills after every module." },
      { t: "Project", d: "Real briefs → portfolio pieces." },
      { t: "Checkpoint", d: "Quizzes that test decisions." },
      { t: "Ship", d: "A reviewed piece that gets you hired." },
    ],
    whyLabel: "Why Mohamed Tarek",
    whyTitleA: "Courses built like",
    whyTitleI: "campaigns",
    whyTitleB: ".",
    why: [
      { t: "A director, not a narrator", d: "Every lesson comes from live client work — campaigns, identities, films that shipped. You learn decisions, not buttons." },
      { t: "3–5 hours, zero filler", d: "Courses are edited like films. If a minute doesn't change how you work, it's cut." },
      { t: "Projects over playback", d: "Every module ends with your hands on a real brief. Finishing means a portfolio, not a watch history." },
      { t: "Arabic-friendly, world-standard", d: "Taught for the MENA market, benchmarked against global studio craft." },
    ],
    instructorLabel: "The instructor",
    workedWithLabel: "Companies & academies he's worked with",
    instructorTitleA: "Taught by a working",
    instructorTitleI: "art director",
    instructorTitleB: ".",
    instructorBio:
      "Mohamed Tarek leads brand, campaign and motion work across Egypt, Saudi Arabia and Kuwait — and has taught 1,200+ students across four academies. This school is his method, distilled: the exact workflows his teams use on paying briefs.",
    instructorCta: "Meet the instructor",
    brandsNote: "Brands his work has served",
    bundleLabel: "The AI stack",
    bundleCta: "Grab the stack ✦",
    bundleNote: "vs. buying separately",
    testimonialsLabel: "Student words",
    testimonialsTitleA: "They came for a tool.",
    testimonialsTitleI: "They left with a craft",
    testimonialsTitleB: ".",
    faqLabel: "Questions",
    faqTitle: "Before you ask —",
    faqCta: "All questions answered",
    finalLabel: "Begin",
    finalTitleA: "Two courses are",
    finalTitleI: "free",
    finalTitleB: ". What's your excuse?",
    finalSub: "Start Photoshop Mastery right now — the complete course, final project included. No card, no trial, no catch.",
    finalCta: "Start free now ✦",
    finalAlt: "or browse all courses",

    // -- why take this at all — outcomes first, right after the hero -------
    rtbLabel: "What you get out of it",
    rtbTitleA: "Not lessons.",
    rtbTitleI: "A skill",
    rtbTitleB: " that pays.",
    rtbItems: [
      {
        t: "Skills clients pay for",
        d: "The exact software and AI pipeline agencies bill every day — taught from real briefs, not theory.",
      },
      {
        t: "A portfolio piece per course",
        d: "Every course ends in a real project I review personally. That finished piece is what gets you hired — not a certificate.",
      },
      {
        t: "Earn it back on job #1",
        d: "Each paid course costs less than one freelance brief pays. Finish the course, take one job, you're already in profit.",
      },
      {
        t: "Judge it free first",
        d: "Photoshop and Illustrator are complete and free — no card, no trial. Watch how I teach, then decide if the paid tracks deserve you.",
      },
    ],

    // -- "why here, not anyone else" comparison ---------------------------
    whyMeLabel: "The difference",
    whyMeTitleA: "Any course teaches",
    whyMeTitleI: "the tool.",
    whyMeTitleB: " Here you leave with paid work.",
    whyMeSub:
      "Compare before you enroll anywhere — including here. This is exactly what you get on each side.",
    themCol: "A typical course",
    meCol: "With Mohamed Tarek",
    whyMeRows: [
      {
        them: "Recorded theory and stock-photo exercises",
        me: "Real client briefs — the same files real brands approved",
      },
      {
        them: "A certificate nobody ever checks",
        me: "A finished portfolio project, reviewed by me personally",
      },
      {
        them: "Watch alone; questions go nowhere",
        me: "A direct WhatsApp line to the instructor",
      },
      {
        them: "Taught by a full-time teacher",
        me: "Taught by an art director still shipping for real brands",
      },
      {
        them: "Pay first, then find out",
        me: "Two complete courses free — judge the teaching before paying a pound",
      },
      {
        them: "Priced like a subscription you forget",
        me: "Priced against one freelance job — brief #1 pays it back",
      },
    ],
    whyMeCta: "Test me on the free courses first →",
    whyMeNote: "If the free ones don't convince you, don't buy the paid ones. Fair?",

    // -- objection handling (above the final CTA) -------------------------
    objLabel: "Still thinking? Fair.",
    objections: [
      {
        q: "I'm a total beginner — will I keep up?",
        a: "Every track starts from zero. Photoshop and Illustrator are free and complete — start there. No card, no catch.",
      },
      {
        q: "Why would two full courses be free?",
        a: "Because it's the honest way to prove the teaching. Watch them, judge the quality, then decide if the paid tracks are worth it.",
      },
      {
        q: "I don't have time for this.",
        a: "Each course is 3–5 focused hours cut into short lessons with zero filler. A week of evenings finishes a track.",
      },
      {
        q: "And if I can't find clients after?",
        a: "Your final project is a real brief, personally reviewed — that's the portfolio piece that gets replies. The pricing lessons show you how to quote it.",
      },
    ],
  },

  catalog: {
    metaTitle: "Courses — Free Photoshop & Illustrator + Pro Motion, Video & AI",
    kicker: "The drops",
    titleA: "Choose your",
    titleI: "craft",
    titleB: ".",
    sub: "Photoshop & Illustrator — free, forever. After Effects, Premiere and two AI tracks — priced against one freelance job, not one course. All: projects, quizzes, reviewed final projects.",
    all: "All",
    filterDesign: "Design",
    filterMotion: "Motion & Video",
    filterAi: "AI Production",
    bundleCard: "The AI Production Stack",
    bundleCardSub: "AI Photoshoot + AI Video — one enrollment, one pipeline",
    empty: "No courses match this filter. Clear it or try a different search.",
    searchPh: "Search courses, tools, skills…",
    filterFree: "Free",
    filterPremium: "Premium",
    popular: "Most popular",
    recommended: "Recommended",
    results: "results",
  },

  course: {
    breadcrumbCourses: "Courses",
    heroIncludes: "This course includes",
    includesItems: [
      "Lifetime access, updates included",
      "Practical projects & working files",
      "Checkpoint quizzes",
      "Final project with a personal review",
      "Downloadable resources",
      "WhatsApp support from the instructor",
    ],
    whatYouLearn: "What you walk out with",
    pathLabel: "Learning path",
    curriculumLabel: "Curriculum",
    curriculumNote: "Editorial index — every lesson, every minute, no padding.",
    projectsLabel: "Practical projects",
    resourcesLabel: "Downloadable resources",
    finalProjectLabel: "Final project",
    deliverables: "You deliver",
    outcomeLabel: "The outcome",
    outcomeTitle: "Finish it. Ship it.",
    outcomeNote:
      "Complete every lesson, pass the checkpoint quiz and submit the final project — you leave with a reviewed portfolio piece, not just a watch history.",
    instructorLabel: "Your instructor",
    reviewsLabel: "Student reviews",
    faqLabel: "Course FAQ",
    enrollTitle: "Enroll in this course",
    bundleHint: "Part of the AI Production Stack —",
    bundleHintCta: "see the bundle",
    guarantee: "7-day money-back guarantee — no forms, one WhatsApp message.",
    startFreeNote: "Free forever. No card required.",
    alreadyEnrolled: "You're enrolled —",
    goToCourse: "go to the course →",
    audienceLabel: "Who it's for",
    toolsLabel: "Tools covered",
    relatedLabel: "Pairs well with",
    viewingNow: "designers on this page right now",
    showcaseLabel: "Made with this course",
    showcaseNote: "Straight from the exact pipeline you're about to learn — real client output, no cherry-picking.",
  },

  bundle: {
    metaTitle: "The AI Production Stack — AI Photoshoot + AI Video",
    kicker: "The AI stack",
    includes: "Two courses. One pipeline.",
    note: "The complete camera-less campaign stack — stills, motion, and the pricing to sell both.",
    totalRuntime: "total runtime",
    totalLessons: "lessons",
    projectsNote: "6 practical projects + 2 reviewed final projects — a portfolio, not a playlist",
    cta: "Enroll in the stack ✦",
    vs: "bought separately",
    save: "you save",
  },

  auth: {
    loginTitle: "Welcome back.",
    loginSub: "Your courses, progress and projects are waiting.",
    registerTitle: "Start your craft.",
    registerSub: "One account — every course, project and review lives here.",
    name: "Full name",
    namePh: "e.g. Salma Ibrahim",
    email: "Email",
    emailPh: "you@example.com",
    password: "Password",
    passwordPh: "••••••••",
    loginBtn: "Log in →",
    registerBtn: "Create account →",
    orRegister: "New here?",
    orLogin: "Already have an account?",
    registerLink: "Create an account",
    loginLink: "Log in",
    demoNote: "Demo platform: your account lives in this browser only — no server, no spam, no password stored.",
    previewLabel: "Or jump straight in",
    previewStudent: "Preview as student",
    previewAdmin: "Preview as admin",
    teamPrompt: "An agency or team? No account needed —",
    teamLink: "see team training →",
    phone: "Phone (WhatsApp)",
    phonePh: "+20 1x xxx xxxx",
    errPhone: "Add a phone number so course access and support can reach you.",
    socialLabel: "or continue with",
    socialNote: "Demo: social sign-in connects instantly in this browser.",
    errName: "Please enter your name.",
    errEmail: "Please enter a valid email.",
  },

  checkout: {
    metaTitle: "Checkout",
    kicker: "Checkout",
    title: "Almost in.",
    orderLabel: "Your order",
    payLabel: "Payment method",
    instapay: "InstaPay",
    vodafone: "Vodafone Cash",
    manualNote:
      "Transfer the amount, then tap the button below — send your payment screenshot on WhatsApp and your access is activated personally, usually within minutes.",
    gatewaysSoon: "Card payments (Paymob · Fawry · valU) — arriving soon.",
    total: "Total",
    promoLabel: "Promo code",
    promoPh: "MT-XXXX",
    promoApply: "Apply",
    promoApplied: "Code applied ✓",
    promoInvalid: "That code isn't valid here — codes are personal, one per browser. Scratch yours in the gift popup.",
    promoOff: "Promo discount",
    confirmBtn: "I've paid — confirm on WhatsApp ✦",
    freeBtn: "Enroll free — instant access ✦",
    backTo: "Back to course",
    secure: "Manual, human-verified enrollment — the same flow 1,200+ students used.",
    loginFirst: "Log in or create an account to complete enrollment.",
  },

  success: {
    enrollTitle: "You're in.",
    enrollSub: "Your enrollment is confirmed. Your first lesson is one click away — momentum matters, start now.",
    goDashboard: "Go to my learning →",
    startCourse: "Start the course ✦",
  },

  dash: {
    metaTitle: "My Learning",
    kicker: "Student dashboard",
    greetingM: "Good morning",
    greetingA: "Good afternoon",
    greetingE: "Good evening",
    subEmpty: "Your desk is clear. Pick a course and make it messy.",
    sub: "Pick up exactly where you left off.",
    accountCta: "Account settings",
    goalLabel: "Weekly goal",
    goalOf: "of",
    goalUnit: "h this week",
    goalEdit: "Adjust",
    goalHint: "hours per week",
    goalDone: "Goal cleared — monster. ✦",
    coursesLabel: "My courses",
    addCourse: "Add a course",
    tabActive: "Active",
    tabArchived: "Archived",
    archive: "Archive",
    unarchive: "Restore",
    archivedEmpty: "Nothing archived — everything's in play.",
    assignmentsLabel: "My assignments",
    aStatus: {
      done: "Completed",
      review: "In review",
      progress: "In progress",
      upcoming: "Upcoming",
    },
    qualified: "Qualified",
    sessionsLabel: "Upcoming sessions",
    sessionJoin: "Join room",
    sessionBy: "with Mohamed Tarek",
    statsLabel: "Study statistics",
    statsUnit: "minutes / day",
    statsEmpty: "Finish a lesson and the bars start moving.",
    calendarLabel: "Calendar",
    doubtLabel: "Ask a doubt",
    doubtPh: "Stuck on a lesson? Type your question…",
    doubtSend: "Send",
    doubtNote: "Lands straight in the instructor's WhatsApp.",
    continueLabel: "Continue",
    enrolledLabel: "My courses",
    progressWord: "complete",
    browseCta: "Browse the catalog →",
    statsLessons: "lessons completed",
    statsMinutes: "minutes of craft",
    statsQuizzes: "quizzes cleared",
    quizReady: "Checkpoint quiz ready",
    finalStep: "Final step: pass the checkpoint quiz",
  },

  learn: {
    curriculum: "Curriculum",
    nowPlaying: "Now playing",
    comingSoon: "Video — publishing soon",
    playerNote: "Lessons are being filmed and published module by module. Progress tracking, resources and quizzes are live now.",
    markDone: "Mark lesson complete",
    markedDone: "Completed ✓",
    next: "Next lesson →",
    prev: "← Previous",
    resources: "Resources",
    resourceGet: "Download",
    resourceLocked: "Enroll to download",
    quizTitle: "Checkpoint quiz",
    quizIntro: "Six decisions. Pass 5 to clear the checkpoint — this is where knowing becomes owning.",
    quizStart: "Start the quiz →",
    quizQuestion: "Question",
    quizCheck: "Check answers",
    quizPassed: "Checkpoint cleared ✓",
    quizFailed: "Not yet — review the misses and retry.",
    quizRetry: "Retry",
    quizScore: "Your score",
    progressLabel: "Course progress",
    completedTitle: "Course complete — now go get paid.",
    boardTab: "Notes board",
    boardAdd: "Note",
    boardClear: "Clear board",
    boardClearConfirm: "Clear all notes from this course's board?",
    boardEmpty: "Your board. Drop notes, ideas, timestamps — a FigJam-style page that lives with this course.",
    boardPlaceholder: "Type a note…",
    boardDelete: "Delete note",
    boardHint: "Drag notes anywhere — saved automatically.",
    boardPen: "Pen — draw on the board",
    boardPenHint: "Pen on — draw anywhere.",
    boardErase: "Eraser — remove strokes",
    boardEraseHint: "Eraser on — drag over a stroke to remove it.",
    boardHand: "Hand — move around the board",
    boardHandHint: "Hand on — drag to pan the board.",
    backToDash: "← My learning",
    enrollGate: "Enroll to open the full course",
    enrollGateSub: "The first lessons are free previews — the rest unlocks with enrollment.",
    finalProjectTab: "Final project",
    overviewTab: "Overview",
  },

  profile: {
    metaTitle: "Profile",
    kicker: "Student profile",
    memberSince: "Learning since",
    editName: "Display name",
    phone: "Phone (WhatsApp)",
    changePhoto: "Change photo",
    photoNote: "JPG or PNG — stored in your browser only.",
    saveBtn: "Save changes",
    saved: "Saved ✓",
    dangerLabel: "Session",
    logoutBtn: "Log out",
    resetBtn: "Reset all demo data",
    resetConfirm: "This clears your account, progress and quiz results from this browser. Sure?",
    statsLabel: "Your numbers",
  },

  downloads: {
    metaTitle: "Downloads",
    kicker: "The vault",
    title: "Downloads",
    sub: "Working files, cheat sheets and templates from your enrolled courses.",
    empty: "Enroll in a course to unlock its resource vault.",
    perCourse: "From",
  },

  blogUi: {
    metaTitle: "Blog & Support — Guides, How-tos & Answers",
    kicker: "Blog · Support",
    titleA: "Help, guides &",
    titleI: "answers",
    titleB: ".",
    sub: "Support articles and honest how-tos — enrollment help, learning paths, career sequencing and AI production. Everything you need to get unstuck and keep moving.",
    readMore: "Read →",
    minsRead: "min read",
    relatedCourse: "The course behind this article",
    courseCtaLead: "Want to actually do this?",
    courseCtaBtn: "Start the course →",
    backToBlog: "← All articles",
    faqInPost: "Quick answers",
  },

  faqPage: {
    metaTitle: "FAQ — Enrollment, Courses, Payments & Access",
    kicker: "Questions",
    titleA: "Everything you'd",
    titleI: "ask",
    titleB: ", answered.",
    sub: "Enrollment, payments, courses, tools — if it's not here, WhatsApp me directly.",
    stillCta: "Still curious? Talk to me →",
    items: [
      { q: "How do courses work at Mohamed Tarek?", a: "Every course is 3–5 hours of focused video organized into modules, with drills, real projects, downloadable working files, checkpoint quizzes and a final project. Finish everything and you walk out with a reviewed portfolio piece — the thing that actually gets you hired." },
      { q: "Why are the courses so short?", a: "Because they're edited like films. Ten-hour courses are ten hours because nobody cut them. Mohamed Tarek courses keep only the minutes that change how you work — the rest of your time goes into practice, which is where skill actually forms." },
      { q: "How do I pay?", a: "Visa or Mastercard at checkout. Pay, screenshot the confirmation on WhatsApp if anything looks off, and your access is activated personally — usually within minutes." },
      { q: "Which courses are free, and how are the rest priced?", a: "Photoshop and Illustrator — the two foundations — are completely free, forever: full courses with projects, quizzes and reviewed final projects. After Effects (EGP 1,800), Premiere Pro (EGP 1,050) and the two AI tracks (EGP 2,300 and 2,700) are paid — each a fraction of what a single freelance motion, edit or AI brief pays in the market. The goal is that your first paid job covers the course several times over." },
      { q: "Do I get lifetime access?", a: "Yes. One payment, permanent access, all future updates to that course included." },
      { q: "What if the course isn't for me?", a: "7-day money-back guarantee. One WhatsApp message, no forms, no questions that matter." },
      { q: "Do I get something to show employers?", a: "Something better than a paper credential: finished, personally-reviewed portfolio projects from every course. Employers and clients hire from work, not certificates — this school is built around that truth." },
      { q: "Do I need a powerful computer?", a: "No. Every course is taught on mid-range hardware, with performance workarounds (like Premiere proxies) built into the curriculum." },
      { q: "Is the teaching in Arabic or English?", a: "Lessons are taught in Arabic with English tool vocabulary — the way MENA studios actually talk. The platform itself is fully bilingual." },
      { q: "Can I get training for my team or academy?", a: "Yes — corporate and academy programs run separately (on-site in Egypt, online elsewhere). Reach out via the contact page and I'll reply personally." },
    ],
  },

  admin: {
    metaTitle: "Studio",
    kicker: "The studio — admin",
    welcome: "Welcome back",
    sub: "Revenue, signups and course performance — the whole school on one desk.",
    range: "Last 14 days",
    statRevenue: "Total revenue",
    statStudents: "Students",
    statConversion: "Visit → enroll",
    statCourses: "Live courses",
    chartLabel: "Revenue",
    topLabel: "Top courses",
    topBy: "by revenue",
    signupsLabel: "Latest signups",
    youTag: "this browser",
    locationsLabel: "Where students learn from",
    reviewLabel: "Final projects waiting on you",
    reviewCta: "Review",
    controlsLabel: "Site controls",
    offerText: "Offer ribbon text",
    offerOn: "Show the offer ribbon",
    offerReset: "Restart the 7-day timer",
    save: "Save",
    saved: "Saved ✓",
    editCourses: "Edit courses",
    editorKicker: "The studio — course editor",
    editorTitle: "Every course, editable.",
    editorSub: "Prices, names, covers, fresh lessons — changes apply live across the whole site.",
    newCourseLabel: "Create a new course",
    newCoursePh: "New course name…",
    createBtn: "Create course +",
    draftBadge: "New",
    fModule: "Module / unit name",
    addModuleBtn: "Add module +",
    moduleLabel: "Modules & video lessons",
    noLessons: "No lessons yet — add the first video below.",
    deleteDraft: "Delete this course",
    previewCourse: "Open course page →",
    createdNote: "New courses save in this browser and appear in the catalogue instantly, with their own page.",
    fTitle: "Course title",
    fShort: "Card name",
    fTagline: "Tagline",
    fPrice: "Price (EGP)",
    fCompare: "Compare-at (EGP)",
    fCover: "Cover image path / URL",
    addLessonLabel: "Add a video lesson",
    fLessonTitle: "Lesson title",
    fLessonMins: "Minutes",
    fLessonUrl: "Video URL (YouTube / MP4)",
    addLessonBtn: "Add lesson +",
    extraCount: "fresh drops added",
    resetCourse: "Reset this course",
    resetAll: "Reset all studio edits",
    edited: "Edited",
    open: "View page",
    backToStudio: "← Studio",
    localNote: "Studio demo: edits save in this browser and restyle the live site instantly — prices, cards, checkout, everything.",
    guard: "This desk belongs to the instructor.",
    guardSub: "Log in with the admin account — or preview the studio in one click.",
    guardCta: "Preview as admin ✦",
  },

  training: {
    kicker: "For agencies & teams",
    titleA: "Train the",
    titleI: "whole team",
    titleB: ".",
    sub: "Custom Mohamed Tarek programs for agencies, studios and marketing teams — brand, campaign, motion and AI production. On-site in Egypt, live online everywhere else.",
    formTitle: "Request a team program",
    agency: "Company / agency name",
    pName: "Contact person",
    pNamePh: "Who I'll be talking to",
    pRole: "Their role / title",
    pRoles: ["CEO / Founder", "Marketing manager", "Creative / art director", "HR / L&D lead", "Team lead", "Other"],
    size: "Team size",
    sizes: ["2–5", "6–15", "16–50", "50+"],
    industry: "Industry",
    industries: ["Agency / studio", "Real estate", "F&B / hospitality", "Fashion / retail", "Tech / startup", "Education", "Other"],
    location: "Location",
    locations: ["Egypt", "Saudi Arabia", "UAE", "Kuwait", "Qatar", "Other"],
    website: "Website / portfolio link",
    modeLabel: "Delivery mode",
    modeEg: "🇪🇬 On-site or live online — your choice, since you're in Egypt.",
    modeIntl: "🌍 Live online — full program delivered remotely for teams outside Egypt.",
    submit: "Request the program →",
    note: "Opens your email app with everything pre-filled — I reply personally within 24 hours.",
    consultTitle: "Free strategy consultation",
    consultSub: "For CEOs, founders, owners and marketing managers: a free call — up to 60 minutes — on how AI production can cut your content costs and speed up your output. Happy to assist.",
    consultTag: "Free · up to 60 min",
    cName: "Your name",
    cRole: "Your role",
    cRoles: ["CEO", "Founder / owner", "Marketing manager", "Other executive"],
    cCompany: "Company",
    cContact: "Email or WhatsApp number",
    cTime: "Preferred time",
    cTimes: ["Morning", "Afternoon", "Evening"],
    cSubmit: "Book the free call →",
    cNote: "Booked over WhatsApp — you'll get a reply the same day.",
    tabProgram: "Team program",
    tabConsult: "Free consult · 60 min",
    tabHint: "Pick a lane — one form, two minutes.",
    bannerTag: "Mohamed Tarek for business",
  },

  contact: {
    metaTitle: "Contact — Talk to the Instructor",
    kicker: "Contact",
    titleA: "Talk to a",
    titleI: "person",
    titleB: ". Me, specifically.",
    sub: "Enrollment help, team training, academy partnerships or just a question about your path — I answer personally, usually same-day.",
    waCta: "WhatsApp me →",
    emailCta: "Email me →",
    formName: "Your name",
    formEmail: "Your email",
    formTopic: "Topic",
    topics: ["Course question", "Enrollment / payment help", "Team or academy training", "Something else"],
    formMsg: "Your message",
    formSend: "Send message →",
    formNote: "Opens your email app with everything pre-filled.",
    trainingTitle: "Companies & academies",
    trainingNote: "Custom programs for teams — brand, campaign, motion and AI production. On-site in Egypt, online everywhere else.",
  },

  legal: {
    kicker: "Legal",
    updated: "Last updated",
    terms: {
      title: "Terms of Service",
      sections: [
        { h: "The service", p: "Mohamed Tarek provides online design education: video lessons, projects, resources, quizzes and final-project reviews. Access to paid courses is granted per person after payment confirmation and is not transferable or shareable." },
        { h: "Enrollment & access", p: "Paid enrollments grant lifetime access to the purchased course, including future updates to that course. Free courses may be updated, extended or restructured at any time." },
        { h: "Acceptable use", p: "Course videos, files and resources are licensed to you personally. Redistributing, reselling, screen-recording for sharing, or uploading materials elsewhere terminates access without refund and may carry legal consequences." },
        { h: "Completion", p: "Course completion means all lessons finished, checkpoint quizzes passed and a final project submitted. Final projects receive a personal review from the instructor." },
        { h: "Refunds", p: "A 7-day money-back guarantee applies to paid courses — see the Refund Policy for the exact terms." },
        { h: "Changes", p: "These terms may be updated; continued use after changes constitutes acceptance. Material changes will be announced on the platform." },
      ],
    },
    privacy: {
      title: "Privacy Policy",
      sections: [
        { h: "What this demo stores", p: "This platform currently runs fully in your browser: your account name, email, course progress and quiz results are stored in your browser's local storage only. No server receives, processes or sells this data." },
        { h: "Payments", p: "Payments run through InstaPay, Vodafone Cash or (soon) licensed gateways. We never see or store card numbers; payment confirmation happens via WhatsApp screenshots you choose to send." },
        { h: "Communication", p: "WhatsApp and email conversations are used solely to activate access, provide support and — only with your consent — share course updates." },
        { h: "Analytics", p: "If analytics are enabled, they are aggregate and anonymous: page views and course popularity, never personal learning data tied to your identity." },
        { h: "Your rights", p: "You can clear all locally-stored data anytime from your Profile page, and request deletion of any support-conversation history via WhatsApp or email." },
      ],
    },
    refunds: {
      title: "Refund Policy",
      sections: [
        { h: "The guarantee", p: "Every paid course carries a 7-day money-back guarantee, counted from access activation. If it isn't right for you, one WhatsApp message gets your money back — no forms, no friction." },
        { h: "How refunds work", p: "Send your enrollment details on WhatsApp within 7 days. Refunds are returned via the same method you paid (InstaPay / Vodafone Cash) within 3 business days." },
        { h: "Fair use", p: "The guarantee exists to remove risk, not to lend content: accounts that complete more than 60% of a course or download its full resource vault before requesting a refund may be reviewed individually." },
        { h: "Bundles", p: "Bundle refunds work identically within the 7-day window. Partial bundle refunds (keeping one course) are handled personally — just ask." },
      ],
    },
  },

  footer: {
    blurb: "The online design school of art director Mohamed Tarek — short, premium courses that end in real projects, real skills and a real portfolio.",
    learnCol: "Learn",
    platformCol: "Support",
    companyCol: "School",
    legalCol: "Legal",
    connectCol: "Connect",
    payLabel: "We accept",
    followLabel: "Follow the work",
    rights: "All rights reserved.",
    backTop: "Back to top ↑",
    madeIn: "Taught from Egypt · Trusted across MENA",
  },

  notFound: {
    kicker: "404",
    titleA: "This page didn't pass the",
    titleI: "checkpoint quiz",
    titleB: ".",
    sub: "The lesson you're looking for moved, graduated or never enrolled. Let's get you back on the path.",
    home: "Back home →",
    courses: "Browse courses",
  },
};

const ar: typeof en = {
  nav: {
    courses: "الدورات",
    bundle: "الحزمة",
    instructor: "المدرّب",
    blog: "المدونة",
    faq: "الأسئلة الشائعة",
    contact: "تواصل معنا",
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    dashboard: "تعلّمي",
    account: "إعدادات الحساب",
    studio: "الاستوديو",
    offers: "العروض",
    startFree: "ابدأ مجانًا ✦",
    allCourses: "كل الدورات ←",
    training: "الشركات",
    roleTag: "· الإخراج البصري وإنتاج الذكاء الاصطناعي",
  },

  promo: {
    tag: "عروض الإطلاق · تنتهي قريبًا",
    codeLabel: "كودك الشخصي",
    codeHint: "اكشط لتكشفه · خصم إضافي 5% عند الدفع",
    cta: "احصل على العرض ←",
    dismiss: "لاحقًا",
    seeAll: "كل العروض",
    shuffleHint: "اضغط على الرزمة للعرض التالي",
    cardOf: "من",
  },

  offersPage: {
    metaTitle: "العروض — حزم الدورات وخصومات الإطلاق",
    kicker: "العروض",
    titleA: "اختر",
    titleI: "خطتك",
    titleB: ".",
    sub: "ثلاث حزم جنبًا إلى جنب — كل واحدة أرخص من مجموع دوراتها، وكلها تسترد ثمنها من أول عمل مدفوع.",
    includes: "ماذا تضم هذه الحزمة",
    runtime: "إجمالي المدة",
    lessonsWord: "درسًا",
    save: "توفّر",
    cta: "احصل على الحزمة ✦",
    best: "أفضل قيمة",
    codeNote: "لديك كود خصم؟ يُطبَّق في صفحة الدفع.",
    perOnce: "دفعة واحدة · وصول مدى الحياة",
    compareLabel: "ما بالداخل، جنبًا إلى جنب",
    featCourses: "الدورات المشمولة",
    featHours: "ساعات المنهج",
    featProjects: "مشاريع نهائية بمراجعة",
    featAE: "أفتر إفكتس — موشن",
    featPr: "بريمير برو — مونتاج",
    featAiPhoto: "التصوير بالذكاء الاصطناعي",
    featAiVideo: "توليد الفيديو بالذكاء الاصطناعي",
    featSupport: "دعم واتساب",
    featLifetime: "تحديثات مدى الحياة",
    tierEditors: "مسار المونتير",
    tierStack: "مسار المال بالذكاء الاصطناعي",
    tierMaster: "كل شيء. كله.",
  },

  promptFixer: {
    kicker: "مسار مجاني · لنصلحه معًا",
    titleA: "الصق أي برومبت.",
    titleI: "وشاهده يتحسّن",
    titleB: ".",
    sub: "قائمة الفحص نفسها التي أُجريها على كل توليد لعملائي — مجانًا. الصق البرومبت وشاهد ما يضيفه المخرج الفني.",
    placeholder: "مثال: صورة لزجاجة عطر على طاولة…",
    fixBtn: "حسّن البرومبت ✦",
    fixedLabel: "النسخة المُخرَجة",
    tipsLabel: "ما الذي كان ناقصًا",
    copyBtn: "نسخ",
    copied: "تم النسخ ✓",
    emptyTip: "اكتب برومبت أولًا — ولو سطرًا واحدًا.",
    tooShort: "أقصر من أن يُخرَج. صِف اللقطة في 8 كلمات على الأقل — الموضوع والمكان والمزاج — وسأتولى الباقي.",
    grammarTip: "رُتّبت القواعد والإملاء ليقرأه النموذج بوضوح.",
    humanTitle: "من في الكادر؟",
    humanNote: "هناك شخص في هذا البرومبت. النماذج تنجرف لوجوه عامة — الجنسية والعمر والمكان تُثبّت اختيار الشخصية.",
    natLabel: "الجنسية",
    natPh: "مثال: مصري",
    ageLabel: "العمر",
    agePh: "مثال: 27",
    placeLabel: "المكان",
    placePh: "مثال: شقة مشمسة في القاهرة",
    humanApply: "أضِف وأخرِج ✦",
    tips: {
      lens: "لا توجد عدسة. البعد البؤري هو طريقتك في إخراج المنظور — عدسة 85mm تُجمّل المنتجات والوجوه، و35mm تمنح سياقًا أوسع.",
      light: "لا يوجد اتجاه للإضاءة. الضوء هو الصورة — سمِّ نوعه وجهته: «إضاءة نافذة ناعمة من يسار الكاميرا».",
      comp: "لا يوجد تكوين. أخبر الكادر أين يتنفس: مساحة فارغة للعنوان، وتوزيع وفق قاعدة الأثلاث.",
      palette: "لا يوجد عالم لوني. لوحة محددة («كهرماني دافئ هادئ») تحافظ على اتساق الحملة كاملة.",
      constraints: "لا توجد قيود. «بدون نصوص، بدون شعارات، عمق ميدان ضحل» هو ما يمنع الانجراف نحو صور مخزون عامة.",
      subject: "ابدأ بموضوع ومشهد محددين — النموذج لا يستطيع تخمين ما يهمك.",
      human: "ثُبّت اختيار الشخصية: أُضيفت الجنسية والعمر والمكان — هذا ما يمنع الوجوه العامة.",
    },
    upsell: "هذه القائمة، مُطبَّقة لقطة بعد لقطة حتى تصبح غريزة — هذه هي الدورة كلها.",
  },

  offer: {
    text: "عرض الإطلاق — حزمة إنتاج الذكاء الاصطناعي بـ 3,950 ج.م بدلًا من 5,000",
    ends: "ينتهي العرض خلال",
    cta: "احصل عليه",
    days: "ي",
    hours: "س",
    mins: "د",
    secs: "ث",
  },

  common: {
    enroll: "اشترك الآن ✦",
    enrollFree: "ابدأ التعلّم مجانًا ✦",
    continueLearning: "أكمل التعلّم",
    viewCourse: "عرض الدورة",
    lessons: "درسًا",
    lesson: "درس",
    hours: "ساعات",
    modules: "وحدات",
    projects: "مشاريع",
    level: "المستوى",
    students: "طالب",
    graduates: "خريج",
    academies: "أكاديميات",
    free: "مجاني",
    premium: "مدفوع",
    save: "وفّر",
    enrolled: "مشترك ✓",
    completed: "مكتمل",
    inProgress: "قيد التقدم",
    notStarted: "لم يبدأ",
    by: "بواسطة",
    back: "رجوع",
    close: "إغلاق",
    comingSoon: "قريبًا",
    downloadPng: "تنزيل PNG",
    minutesShort: "د",
    hoursShort: "س",
    freePreview: "معاينة مجانية",
    locked: "مقفل",
    rating: "التقييم",
    reviewsWord: "مراجعة",
    of: "من",
    home: "الرئيسية",
  },

  home: {
    kicker: "محمد طارق — ليس موقع دورات آخر",
    heroA: "امتلك الحرفة.",
    heroI: "تفوّق تصميمًا",
    heroB: "على الجميع.",
    heroSub:
      "فوتوشوب وإليستريتور — مجانًا، كاملَين، للأبد. أفتر إفكتس وبريمير ومسارات الذكاء الاصطناعي تكلّف جزءًا رمزيًا مما يدفعه عمل مستقل واحد. تعلّم المهارة هذا الأسبوع، واستردّها من أول مشروع.",
    ctaPrimary: "ابدأ مجانًا ✦",
    ctaSecondary: "تصفّح الدورات",
    heroCardTag: "مجاني — دورة كاملة",
    heroStickers: ["ابدأ بدورتين مجانًا", "السعر مقابل عمل مستقل واحد", "بلا حشو"],
    scroll: "مرّر",
    marquee: ["فوتوشوب — مجاني", "إليستريتور — مجاني", "أفتر إفكتس — احترافي", "بريمير برو — احترافي", "التصوير بالذكاء الاصطناعي — مميز", "فيديو الذكاء الاصطناعي — مميز", "استردّه من أول مشروع", "بلا حشو", "من الصفر إلى الاحتراف"],
    statsLabel: "السجل",
    stats: {
      graduates: "خريجًا تعلّموا على يديه",
      academies: "أكاديميات تُدرّس منهجه",
      hours: "ساعة من منهج بلا حشو",
      lessons: "درسًا تطبيقيًا",
    },
    manLabel: "الاتفاق",
    freeTitle: "ابدأ مجانًا: فوتوشوب وإليستريتور كاملَين.",
    freeBody: "الأساسان — دورتان كاملتان بمشاريع واختبارات ومشروع نهائي بمراجعة شخصية، بصفر جنيه. تعلّم الحرفة التي يُبنى عليها كل شيء. بلا بطاقة، بلا شروط خفية.",
    freeTag: "0 ج.م — للأبد",
    paidTitle: "مسارات الذكاء الاصطناعي — سعرها مقابل عمل مستقل واحد.",
    paidBody: "التصوير والفيديو بالذكاء الاصطناعي هما ما تدفع فيه العلامات ميزانيات ضخمة الآن. كل دورة تكلّف جزءًا رمزيًا مما يدفعه مشروع واحد — أنهِها هذا الأسبوع واستردّ ثمنها من أول عمل مدفوع.",
    paidTag: "استردّه من أول مشروع",
    coursesLabel: "حرفة البرامج",
    coursesTitleA: "أتقن",
    coursesTitleI: "الأدوات",
    coursesTitleB: ".",
    coursesNote: "فوتوشوب وإليستريتور مجانًا للأبد · أفتر إفكتس وبريمير بسعر احترافي — كلها كاملة بمشاريع واختبارات ومشروع نهائي بمراجعة.",
    featuredLabel: "مميز · التصوير بالذكاء الاصطناعي",
    featuredNote: "إن كنت هنا لتكسب، فابدأ من هنا.",
    featuredVideoLabel: "مميز · فيديو الذكاء الاصطناعي",
    featuredVideoNote: "بلا كاميرا. بلا طاقم. جاهز للبث.",
    featuredCta: "افتح الدورة ✦",
    featuredBrowse: "تصفّح كل شيء",
    econLabel: "الحسابات",
    econTitleA: "السعر مقابل",
    econTitleI: "عمل مستقل واحد",
    econTitleB: "، لا دورة واحدة.",
    econ: [
      { n: "+8,000", u: "ج.م", l: "ما يدفعه مشروع موشن أو مونتاج أو ذكاء اصطناعي واحد — وغالبًا أكثر" },
      { n: "1,050", u: "ج.م", l: "دورة بريمير برو الكاملة — مرة واحدة، للأبد" },
      { n: "مشروعك الأول", u: "", l: "يسدّد ثمن الدورة. وكل ما بعده ربح صافٍ." },
    ],
    storyLabel: "قصة مميزة",
    storyQuote:
      "أنهيت حزمة الذكاء الاصطناعي يوم جمعة. بعد أسبوعين سعّرت أول إعلان لي بأكثر من راتبي الشهري — ولم يتردد العميل. درس التسعير وحده سدّد كل شيء.",
    storyName: "خالد عماد",
    storyRole: "مصمم مستقل ← إنتاج بالذكاء الاصطناعي",
    storyChips: ["أول عمل مدفوع: 3 أسابيع", "متفرّغ الآن للعمل الحر", "خريج حزمة إنتاج الذكاء الاصطناعي"],
    giftTag: "هدية لمسيرتك",
    giftHint: "اضغط لفتحها ✦",
    outcomesLabel: "الدليل",
    outcomesTitleA: "نتائج،",
    outcomesTitleI: "لا وعود",
    outcomesTitleB: ".",
    outcomes: [
      { n: 1200, s: "+", l: "طالب تعلّموا عبر أربع أكاديميات" },
      { n: 78, s: "%", l: "من المُكملين يحصلون على عمل مدفوع خلال 3 أشهر" },
      { n: 21, s: "", l: "يومًا في المتوسط حتى أول عمل مدفوع بعد حزمة الذكاء الاصطناعي" },
      { n: 96, s: "%", l: "نسبة إكمال — الدورات القصيرة تُنهى فعلًا" },
    ],
    galleryLabel: "صُنع بالمنهج",
    communityNote:
      "كل طالب ينضم إلى غرفة واتساب الخاصة — النقد الفني وفرص العمل والدورات الجديدة تصل هناك أولًا.",
    trustChips: ["دعم شخصي عبر واتساب", "وصول مدى الحياة", "التدريس بالعربية"],
    instructorChipsLabel: "قطاعات خدمها بعمله",
    instructorChips: ["السيارات", "العقارات", "الطبي", "المطاعم والضيافة", "الأزياء والتجزئة", "التجارة الإلكترونية", "السينما والأفلام", "الرياضة", "تقنية الأغذية", "التعليم"],
    pathLabel: "المنهج",
    pathTitleA: "من الصفر ←",
    pathTitleI: "الاحتراف",
    pathTitleB: "، في خمس خطوات.",
    pathNote: "كل دورة، القوس نفسه.",
    path: [
      { t: "تعلّم", d: "ملف عمل مفتوح. شاهد، أوقف، طبّق." },
      { t: "تمرّن", d: "تدريبات بعد كل وحدة." },
      { t: "مشروع", d: "مهام حقيقية ← أعمال بورتفوليو." },
      { t: "نقطة تفتيش", d: "اختبارات تقيس القرارات." },
      { t: "سلّم", d: "عمل مُراجَع يُوظّفك." },
    ],
    whyLabel: "لماذا محمد طارق",
    whyTitleA: "دورات مبنية مثل",
    whyTitleI: "الحملات",
    whyTitleB: ".",
    why: [
      { t: "مخرج فني، لا مُلقِّن", d: "كل درس من عمل حقيقي لعملاء — حملات وهويات وأفلام سُلِّمت فعلًا. تتعلم القرارات لا الأزرار." },
      { t: "ساعات قليلة، بلا حشو", d: "الدورات تُمنتَج كالأفلام. أي دقيقة لا تغيّر طريقة عملك، تُحذف." },
      { t: "مشاريع لا مشاهدات", d: "كل وحدة تنتهي ويداك على مهمة حقيقية. الإكمال يعني بورتفوليو، لا سجل مشاهدة." },
      { t: "عربي الروح، عالمي المعيار", d: "مُدرَّس لسوق المنطقة، ومُقاس على حرفة الاستوديوهات العالمية." },
    ],
    instructorLabel: "المدرّب",
    workedWithLabel: "شركات وأكاديميات عمل معها",
    instructorTitleA: "يدرّسك مدير فني",
    instructorTitleI: "يعمل فعلًا",
    instructorTitleB: ".",
    instructorBio:
      "يقود محمد طارق أعمال العلامات والحملات والموشن في مصر والسعودية والكويت — ودرّس أكثر من 1,200 طالب عبر أربع أكاديميات. هذه المدرسة هي خلاصة منهجه: مسارات العمل نفسها التي تستخدمها فرقه في مشاريع مدفوعة.",
    instructorCta: "تعرّف على المدرّب",
    brandsNote: "علامات خدمها عمله",
    bundleLabel: "حزمة الذكاء الاصطناعي",
    bundleCta: "احصل على الحزمة ✦",
    bundleNote: "مقابل الشراء المنفصل",
    testimonialsLabel: "كلمات الطلاب",
    testimonialsTitleA: "جاؤوا من أجل أداة.",
    testimonialsTitleI: "وغادروا بحرفة",
    testimonialsTitleB: ".",
    faqLabel: "أسئلة",
    faqTitle: "قبل أن تسأل —",
    faqCta: "كل الأسئلة مُجابة",
    finalLabel: "ابدأ",
    finalTitleA: "دورتان",
    finalTitleI: "مجانيتان",
    finalTitleB: ". فما عذرك؟",
    finalSub: "ابدأ إتقان فوتوشوب الآن — الدورة كاملة بمشروعها النهائي. بلا بطاقة، بلا فترة تجربة، بلا شروط.",
    finalCta: "ابدأ مجانًا الآن ✦",
    finalAlt: "أو تصفّح كل الدورات",

    // -- لماذا تأخذ الدورة أصلًا — النتائج أولًا بعد البانر مباشرة -----------
    rtbLabel: "ما الذي ستخرج به",
    rtbTitleA: "ليست دروسًا.",
    rtbTitleI: "مهارة",
    rtbTitleB: " تُدفع مقابلها.",
    rtbItems: [
      {
        t: "مهارات يدفع العملاء مقابلها",
        d: "نفس البرامج وخط إنتاج الذكاء الاصطناعي الذي تفوتر به الوكالات كل يوم — تدريس من مشاريع حقيقية، لا نظريات.",
      },
      {
        t: "قطعة بورتفوليو من كل دورة",
        d: "كل دورة تنتهي بمشروع حقيقي أراجعه بنفسي. هذه القطعة المكتملة هي ما يوظّفك — لا الشهادة.",
      },
      {
        t: "استرد ثمنها من أول عمل",
        d: "كل دورة مدفوعة تكلف أقل مما يدفعه مشروع فريلانس واحد. أنهِ الدورة، خذ عملًا واحدًا، وأنت رابح بالفعل.",
      },
      {
        t: "احكم بنفسك مجانًا أولًا",
        d: "فوتوشوب وإليستريتور كاملتان ومجانيتان — بلا بطاقة ولا فترة تجربة. شاهد طريقة التدريس، ثم قرر إن كانت المسارات المدفوعة تستحقك.",
      },
    ],

    // -- "لماذا هنا وليس أي مكان آخر" ---------------------------------------
    whyMeLabel: "الفرق",
    whyMeTitleA: "أي دورة تعلّمك",
    whyMeTitleI: "الأداة.",
    whyMeTitleB: " هنا تخرج بعملٍ مدفوع.",
    whyMeSub: "قارن قبل أن تسجّل في أي مكان — بما في ذلك هنا. هذا بالضبط ما تحصل عليه في كل جانب.",
    themCol: "دورة تقليدية",
    meCol: "مع محمد طارق",
    whyMeRows: [
      {
        them: "نظريات مسجّلة وتمارين على صور جاهزة",
        me: "ملفات عملاء حقيقية — نفس الأعمال التي اعتمدتها علامات فعلية",
      },
      {
        them: "شهادة لا يتحقق منها أحد",
        me: "مشروع كامل في معرض أعمالك، أراجعه بنفسي شخصيًا",
      },
      {
        them: "تشاهد وحدك وأسئلتك بلا إجابة",
        me: "خط واتساب مباشر مع المدرّب",
      },
      {
        them: "يدرّسها معلّم متفرّغ للتدريس",
        me: "يدرّسها مدير فني ما زال يسلّم أعمالًا لعلامات حقيقية",
      },
      {
        them: "ادفع أولًا ثم اكتشف",
        me: "دورتان كاملتان مجانًا — احكم على التدريس قبل أن تدفع جنيهًا",
      },
      {
        them: "سعر كاشتراك تنساه",
        me: "سعر يعادل مشروعًا مستقلًا واحدًا — أول عمل يسترد ثمنه",
      },
    ],
    whyMeCta: "اختبرني في الدورات المجانية أولًا ←",
    whyMeNote: "إن لم تقنعك الدورات المجانية، لا تشترِ المدفوعة. عادل؟",

    // -- معالجة الاعتراضات (قبل الدعوة الأخيرة) -----------------------------
    objLabel: "ما زلت تفكر؟ من حقك.",
    objections: [
      {
        q: "أنا مبتدئ تمامًا — هل سأستوعب؟",
        a: "كل مسار يبدأ من الصفر. فوتوشوب وإليستريتور مجانيان وكاملان — ابدأ منهما. بلا بطاقة، بلا شروط.",
      },
      {
        q: "لماذا دورتان كاملتان مجانًا؟",
        a: "لأنها الطريقة الأصدق لإثبات جودة التدريس. شاهدهما واحكم بنفسك، ثم قرر إن كانت المسارات المدفوعة تستحق.",
      },
      {
        q: "لا أملك وقتًا لهذا.",
        a: "كل دورة من ٣ إلى ٥ ساعات مركّزة مقسّمة لدروس قصيرة بلا حشو. أسبوع من الأمسيات ينهي مسارًا كاملًا.",
      },
      {
        q: "وإن لم أجد عملاء بعدها؟",
        a: "مشروعك النهائي مبني على ملف حقيقي ويُراجع شخصيًا — هذه هي القطعة التي تجلب الردود. ودروس التسعير تريك كيف تحدد سعرك.",
      },
    ],
  },

  catalog: {
    metaTitle: "الدورات — فوتوشوب وإليستريتور مجانًا + موشن وفيديو وذكاء اصطناعي احترافي",
    kicker: "الإصدارات",
    titleA: "اختر",
    titleI: "حرفتك",
    titleB: ".",
    sub: "فوتوشوب وإليستريتور — مجانًا للأبد. أفتر إفكتس وبريمير ومساران للذكاء الاصطناعي — بسعر عمل مستقل واحد، لا دورة واحدة. الكل: مشاريع واختبارات ومشاريع نهائية بمراجعة.",
    all: "الكل",
    filterDesign: "تصميم",
    filterMotion: "موشن وفيديو",
    filterAi: "إنتاج الذكاء الاصطناعي",
    bundleCard: "حزمة إنتاج الذكاء الاصطناعي",
    bundleCardSub: "التصوير + الفيديو بالذكاء الاصطناعي — اشتراك واحد، خط إنتاج واحد",
    empty: "لا توجد دورات تطابق هذه التصفية. امسحها أو جرّب بحثًا مختلفًا.",
    searchPh: "ابحث عن دورة أو أداة أو مهارة…",
    filterFree: "مجاني",
    filterPremium: "مدفوع",
    popular: "الأكثر شعبية",
    recommended: "مُوصى بها",
    results: "نتيجة",
  },

  course: {
    breadcrumbCourses: "الدورات",
    heroIncludes: "تشمل هذه الدورة",
    includesItems: [
      "وصول مدى الحياة مع التحديثات",
      "مشاريع تطبيقية وملفات عمل",
      "اختبارات نقاط التفتيش",
      "مشروع نهائي بمراجعة شخصية",
      "موارد قابلة للتنزيل",
      "دعم واتساب من المدرّب",
    ],
    whatYouLearn: "بماذا تخرج",
    pathLabel: "مسار التعلّم",
    curriculumLabel: "المنهج",
    curriculumNote: "فهرس تحريري — كل درس، كل دقيقة، بلا حشو.",
    projectsLabel: "مشاريع تطبيقية",
    resourcesLabel: "موارد قابلة للتنزيل",
    finalProjectLabel: "المشروع النهائي",
    deliverables: "ما تُسلّمه",
    outcomeLabel: "النتيجة",
    outcomeTitle: "أنهِها. سلّمها.",
    outcomeNote:
      "أكمل كل الدروس، واجتز اختبار نقطة التفتيش، وسلّم المشروع النهائي — تخرج بعمل بورتفوليو مُراجَع، لا مجرد سجل مشاهدة.",
    instructorLabel: "مدرّبك",
    reviewsLabel: "آراء الطلاب",
    faqLabel: "أسئلة الدورة",
    enrollTitle: "اشترك في هذه الدورة",
    bundleHint: "جزء من حزمة إنتاج الذكاء الاصطناعي —",
    bundleHintCta: "شاهد الحزمة",
    guarantee: "ضمان استرداد خلال 7 أيام — بلا نماذج، رسالة واتساب واحدة.",
    startFreeNote: "مجاني للأبد. لا حاجة لبطاقة.",
    alreadyEnrolled: "أنت مشترك —",
    goToCourse: "اذهب إلى الدورة ←",
    audienceLabel: "لمن هذه الدورة",
    toolsLabel: "الأدوات المشمولة",
    relatedLabel: "تتكامل مع",
    viewingNow: "مصممًا على هذه الصفحة الآن",
    showcaseLabel: "صُنع بهذه الدورة",
    showcaseNote: "من خط الإنتاج نفسه الذي ستتعلمه — نتائج حقيقية لعملاء، بلا انتقاء.",
  },

  bundle: {
    metaTitle: "حزمة إنتاج الذكاء الاصطناعي — تصوير + فيديو",
    kicker: "حزمة الذكاء الاصطناعي",
    includes: "دورتان. خط إنتاج واحد.",
    note: "حزمة الحملات الكاملة بلا كاميرا — صور ثابتة وحركة، وتسعيرٌ لبيعهما معًا.",
    totalRuntime: "إجمالي المدة",
    totalLessons: "درسًا",
    projectsNote: "6 مشاريع تطبيقية + مشروعان نهائيان بمراجعة — بورتفوليو، لا قائمة تشغيل",
    cta: "اشترك في الحزمة ✦",
    vs: "عند الشراء منفصلًا",
    save: "توفّر",
  },

  auth: {
    loginTitle: "أهلًا بعودتك.",
    loginSub: "دوراتك وتقدمك ومشاريعك بانتظارك.",
    registerTitle: "ابدأ حرفتك.",
    registerSub: "حساب واحد — كل دورة ومشروع ومراجعة تعيش هنا.",
    name: "الاسم الكامل",
    namePh: "مثال: سلمى إبراهيم",
    email: "البريد الإلكتروني",
    emailPh: "you@example.com",
    password: "كلمة المرور",
    passwordPh: "••••••••",
    loginBtn: "تسجيل الدخول ←",
    registerBtn: "إنشاء حساب ←",
    orRegister: "جديد هنا؟",
    orLogin: "لديك حساب بالفعل؟",
    registerLink: "أنشئ حسابًا",
    loginLink: "سجّل الدخول",
    demoNote: "منصة تجريبية: حسابك يعيش في متصفحك فقط — لا خادم، لا رسائل مزعجة، لا تخزين لكلمة المرور.",
    previewLabel: "أو ادخل مباشرة",
    previewStudent: "معاينة كطالب",
    previewAdmin: "معاينة كمدير",
    teamPrompt: "شركة أو فريق؟ لا حاجة لحساب —",
    teamLink: "شاهد تدريب الفرق ←",
    phone: "الهاتف (واتساب)",
    phonePh: "+20 1x xxx xxxx",
    errPhone: "أضف رقم هاتف ليصلك الوصول للدورات والدعم.",
    socialLabel: "أو تابع باستخدام",
    socialNote: "تجريبي: تسجيل الدخول الاجتماعي يتصل فورًا في هذا المتصفح.",
    errName: "من فضلك أدخل اسمك.",
    errEmail: "من فضلك أدخل بريدًا صحيحًا.",
  },

  checkout: {
    metaTitle: "الدفع",
    kicker: "الدفع",
    title: "أوشكت على الدخول.",
    orderLabel: "طلبك",
    payLabel: "طريقة الدفع",
    instapay: "إنستا باي",
    vodafone: "فودافون كاش",
    manualNote:
      "حوّل المبلغ ثم اضغط الزر بالأسفل — أرسل لقطة الدفع على واتساب ويُفعَّل وصولك شخصيًا، عادة خلال دقائق.",
    gatewaysSoon: "الدفع بالبطاقات (باي موب · فوري · فاليو) — قريبًا.",
    total: "الإجمالي",
    promoLabel: "كود الخصم",
    promoPh: "MT-XXXX",
    promoApply: "تطبيق",
    promoApplied: "تم تطبيق الكود ✓",
    promoInvalid: "هذا الكود غير صالح هنا — الأكواد شخصية، واحد لكل متصفح. اكشط كودك من نافذة الهدية.",
    promoOff: "خصم الكود",
    confirmBtn: "دفعت — أكّد عبر واتساب ✦",
    freeBtn: "اشترك مجانًا — وصول فوري ✦",
    backTo: "عودة إلى الدورة",
    secure: "اشتراك يدوي بتحقق بشري — المسار نفسه الذي استخدمه أكثر من 1,200 طالب.",
    loginFirst: "سجّل الدخول أو أنشئ حسابًا لإتمام الاشتراك.",
  },

  success: {
    enrollTitle: "أنت في الداخل.",
    enrollSub: "تم تأكيد اشتراكك. درسك الأول على بُعد نقرة — الزخم مهم، فابدأ الآن.",
    goDashboard: "اذهب إلى تعلّمي ←",
    startCourse: "ابدأ الدورة ✦",
  },

  dash: {
    metaTitle: "تعلّمي",
    kicker: "لوحة الطالب",
    greetingM: "صباح الخير",
    greetingA: "مساء الخير",
    greetingE: "مساء الخير",
    subEmpty: "مكتبك نظيف. اختر دورة واملأه شغلًا.",
    sub: "أكمل من حيث توقفت تمامًا.",
    accountCta: "إعدادات الحساب",
    goalLabel: "الهدف الأسبوعي",
    goalOf: "من",
    goalUnit: "س هذا الأسبوع",
    goalEdit: "تعديل",
    goalHint: "ساعات أسبوعيًا",
    goalDone: "أنجزت الهدف — بطل. ✦",
    coursesLabel: "دوراتي",
    addCourse: "أضف دورة",
    tabActive: "نشطة",
    tabArchived: "مؤرشفة",
    archive: "أرشفة",
    unarchive: "استعادة",
    archivedEmpty: "لا شيء في الأرشيف — كل شيء قيد اللعب.",
    assignmentsLabel: "واجباتي",
    aStatus: {
      done: "مكتمل",
      review: "قيد المراجعة",
      progress: "قيد التقدم",
      upcoming: "قادم",
    },
    qualified: "مُجتاز",
    sessionsLabel: "جلسات قادمة",
    sessionJoin: "انضم للغرفة",
    sessionBy: "مع محمد طارق",
    statsLabel: "إحصاءات المذاكرة",
    statsUnit: "دقيقة / يوم",
    statsEmpty: "أنهِ درسًا وستبدأ الأعمدة بالتحرك.",
    calendarLabel: "التقويم",
    doubtLabel: "اسأل سؤالًا",
    doubtPh: "متعثر في درس؟ اكتب سؤالك…",
    doubtSend: "إرسال",
    doubtNote: "يصل مباشرة إلى واتساب المدرّب.",
    continueLabel: "أكمل",
    enrolledLabel: "دوراتي",
    progressWord: "مكتمل",
    browseCta: "تصفّح الدورات ←",
    statsLessons: "درسًا مكتملًا",
    statsMinutes: "دقيقة من الحرفة",
    statsQuizzes: "اختبارًا مُجتازًا",
    quizReady: "اختبار نقطة التفتيش جاهز",
    finalStep: "الخطوة الأخيرة: اجتز اختبار نقطة التفتيش",
  },

  learn: {
    curriculum: "المنهج",
    nowPlaying: "يُعرض الآن",
    comingSoon: "الفيديو — يُنشر قريبًا",
    playerNote: "تُصوَّر الدروس وتُنشر وحدة بعد وحدة. تتبع التقدم والموارد والاختبارات تعمل الآن.",
    markDone: "علّم الدرس مكتملًا",
    markedDone: "مكتمل ✓",
    next: "الدرس التالي ←",
    prev: "→ السابق",
    resources: "الموارد",
    resourceGet: "تنزيل",
    resourceLocked: "اشترك للتنزيل",
    quizTitle: "اختبار نقطة التفتيش",
    quizIntro: "ست قرارات. اجتز 5 لتعبر النقطة — هنا يتحول المعرفة إلى امتلاك.",
    quizStart: "ابدأ الاختبار ←",
    quizQuestion: "سؤال",
    quizCheck: "تحقق من الإجابات",
    quizPassed: "اجتزت النقطة ✓",
    quizFailed: "ليس بعد — راجع الأخطاء وأعد المحاولة.",
    quizRetry: "إعادة",
    quizScore: "نتيجتك",
    progressLabel: "تقدم الدورة",
    completedTitle: "أُنجزت الدورة — والآن اذهب واكسب.",
    boardTab: "لوحة الملاحظات",
    boardAdd: "ملاحظة",
    boardClear: "مسح اللوحة",
    boardClearConfirm: "مسح كل ملاحظات لوحة هذه الدورة؟",
    boardEmpty: "لوحتك. ألقِ ملاحظات وأفكارًا وطوابع زمنية — صفحة بأسلوب FigJam تعيش مع هذه الدورة.",
    boardPlaceholder: "اكتب ملاحظة…",
    boardDelete: "حذف الملاحظة",
    boardHint: "اسحب الملاحظات أينما شئت — تُحفظ تلقائيًا.",
    boardPen: "قلم — ارسم على اللوحة",
    boardPenHint: "القلم مفعّل — ارسم في أي مكان.",
    boardErase: "ممحاة — أزل الخطوط",
    boardEraseHint: "الممحاة مفعّلة — اسحب فوق خط لإزالته.",
    boardHand: "يد — تحرّك في اللوحة",
    boardHandHint: "اليد مفعّلة — اسحب لتحريك اللوحة.",
    backToDash: "→ تعلّمي",
    enrollGate: "اشترك لفتح الدورة كاملة",
    enrollGateSub: "الدروس الأولى معاينات مجانية — والبقية تُفتح بالاشتراك.",
    finalProjectTab: "المشروع النهائي",
    overviewTab: "نظرة عامة",
  },

  profile: {
    metaTitle: "الملف الشخصي",
    kicker: "ملف الطالب",
    memberSince: "يتعلم منذ",
    editName: "اسم العرض",
    phone: "الهاتف (واتساب)",
    changePhoto: "تغيير الصورة",
    photoNote: "JPG أو PNG — تُخزَّن في متصفحك فقط.",
    saveBtn: "حفظ التغييرات",
    saved: "تم الحفظ ✓",
    dangerLabel: "الجلسة",
    logoutBtn: "تسجيل الخروج",
    resetBtn: "إعادة ضبط بيانات التجربة",
    resetConfirm: "سيمسح هذا حسابك وتقدمك ونتائج اختباراتك من هذا المتصفح. متأكد؟",
    statsLabel: "أرقامك",
  },

  downloads: {
    metaTitle: "التنزيلات",
    kicker: "الخزنة",
    title: "التنزيلات",
    sub: "ملفات عمل وأوراق مرجعية وقوالب من دوراتك المشترَك بها.",
    empty: "اشترك في دورة لفتح خزنة مواردها.",
    perCourse: "من",
  },

  blogUi: {
    metaTitle: "المدونة والدعم — أدلة وشروحات وإجابات",
    kicker: "المدونة · الدعم",
    titleA: "مساعدة وأدلة",
    titleI: "وإجابات",
    titleB: ".",
    sub: "مقالات دعم وشروحات صادقة — مساعدة في الاشتراك، ومسارات التعلّم، وترتيب المسيرة، وإنتاج الذكاء الاصطناعي. كل ما تحتاجه لتتجاوز العقبة وتواصل التقدم.",
    readMore: "اقرأ ←",
    minsRead: "دقيقة قراءة",
    relatedCourse: "الدورة وراء هذا المقال",
    courseCtaLead: "تريد أن تفعلها فعلًا؟",
    courseCtaBtn: "ابدأ الدورة ←",
    backToBlog: "→ كل المقالات",
    faqInPost: "إجابات سريعة",
  },

  faqPage: {
    metaTitle: "الأسئلة الشائعة — الاشتراك والدورات والدفع والوصول",
    kicker: "أسئلة",
    titleA: "كل ما كنت",
    titleI: "ستسأله",
    titleB: "، مُجاب.",
    sub: "الاشتراك، الدفع، الدورات، الأدوات — إن لم تجده هنا، راسلني على واتساب مباشرة.",
    stillCta: "ما زلت تتساءل؟ كلّمني ←",
    items: [
      { q: "كيف تعمل الدورات هنا؟", a: "كل دورة من 3 إلى 5 ساعات فيديو مركّز منظم في وحدات، مع تدريبات ومشاريع حقيقية وملفات عمل قابلة للتنزيل واختبارات نقاط تفتيش ومشروع نهائي. أكمل كل شيء وستخرج بعمل بورتفوليو مُراجَع — الشيء الذي يوظّفك فعلًا." },
      { q: "لماذا الدورات قصيرة هكذا؟", a: "لأنها تُمنتَج كالأفلام. دورات العشر ساعات طولها عشر ساعات لأن أحدًا لم يقصّها. دوراتنا تُبقي فقط الدقائق التي تغيّر طريقة عملك — وبقية وقتك يذهب للتمرين، حيث تتكوّن المهارة فعلًا." },
      { q: "كيف أدفع؟", a: "فيزا أو ماستركارد عند الدفع. ادفع، وإن بدا أي شيء غير واضح أرسل لقطة التأكيد على واتساب، ويُفعَّل وصولك شخصيًا — عادة خلال دقائق." },
      { q: "أي الدورات مجانية، وكيف تُسعَّر البقية؟", a: "فوتوشوب وإليستريتور — الأساسان — مجانيتان تمامًا وللأبد: دورات كاملة بمشاريع واختبارات ومشاريع نهائية بمراجعة. أفتر إفكتس (1,800 ج.م) وبريمير برو (1,050 ج.م) ومسارا الذكاء الاصطناعي (2,300 و2,700 ج.م) مدفوعة — كل منها جزء بسيط مما يدفعه السوق في مشروع موشن أو مونتاج أو ذكاء اصطناعي واحد. الهدف أن يغطي أول عمل مدفوع لك ثمن الدورة عدة مرات." },
      { q: "هل أحصل على وصول مدى الحياة؟", a: "نعم. دفعة واحدة، وصول دائم، وكل تحديثات تلك الدورة مشمولة." },
      { q: "ماذا لو لم تناسبني الدورة؟", a: "ضمان استرداد خلال 7 أيام. رسالة واتساب واحدة، بلا نماذج، بلا أسئلة تُذكر." },
      { q: "هل أحصل على ما أعرضه لأصحاب العمل؟", a: "ما هو أفضل من شهادة ورقية: مشاريع بورتفوليو مكتملة ومُراجَعة شخصيًا من كل دورة. أصحاب العمل والعملاء يوظّفون من الأعمال لا الشهادات — وهذه المدرسة مبنية على هذه الحقيقة." },
      { q: "هل أحتاج حاسوبًا قويًا؟", a: "لا. كل دورة مُدرَّسة على عتاد متوسط، مع حلول أداء (مثل بروكسي بريمير) مدمجة في المنهج." },
      { q: "هل التدريس بالعربية أم الإنجليزية؟", a: "الدروس بالعربية مع مصطلحات الأدوات بالإنجليزية — بالطريقة التي تتحدث بها استوديوهات المنطقة فعلًا. والمنصة نفسها ثنائية اللغة بالكامل." },
      { q: "هل يتوفر تدريب لفريقي أو أكاديميتي؟", a: "نعم — برامج الشركات والأكاديميات تُدار بشكل منفصل (حضوريًا في مصر، وأونلاين في أي مكان آخر). تواصل عبر صفحة الاتصال وسأرد شخصيًا." },
    ],
  },

  admin: {
    metaTitle: "الاستوديو",
    kicker: "الاستوديو — الإدارة",
    welcome: "أهلًا بعودتك",
    sub: "الإيرادات والتسجيلات وأداء الدورات — المدرسة كلها على مكتب واحد.",
    range: "آخر 14 يومًا",
    statRevenue: "إجمالي الإيرادات",
    statStudents: "الطلاب",
    statConversion: "زيارة ← اشتراك",
    statCourses: "دورات منشورة",
    chartLabel: "الإيرادات",
    topLabel: "أعلى الدورات",
    topBy: "بالإيراد",
    signupsLabel: "أحدث التسجيلات",
    youTag: "هذا المتصفح",
    locationsLabel: "من أين يتعلم الطلاب",
    reviewLabel: "مشاريع نهائية بانتظارك",
    reviewCta: "راجع",
    controlsLabel: "تحكم الموقع",
    offerText: "نص شريط العرض",
    offerOn: "إظهار شريط العرض",
    offerReset: "إعادة تشغيل عدّاد الأيام السبعة",
    save: "حفظ",
    saved: "تم الحفظ ✓",
    editCourses: "تحرير الدورات",
    editorKicker: "الاستوديو — محرر الدورات",
    editorTitle: "كل دورة، قابلة للتحرير.",
    editorSub: "الأسعار والأسماء والأغلفة والدروس الجديدة — تُطبَّق التغييرات مباشرة عبر الموقع كله.",
    newCourseLabel: "أنشئ دورة جديدة",
    newCoursePh: "اسم الدورة الجديدة…",
    createBtn: "إنشاء الدورة +",
    draftBadge: "جديد",
    fModule: "اسم الوحدة",
    addModuleBtn: "إضافة وحدة +",
    moduleLabel: "الوحدات ودروس الفيديو",
    noLessons: "لا دروس بعد — أضف أول فيديو بالأسفل.",
    deleteDraft: "حذف هذه الدورة",
    previewCourse: "افتح صفحة الدورة ←",
    createdNote: "الدورات الجديدة تُحفظ في هذا المتصفح وتظهر في الكتالوج فورًا بصفحتها الخاصة.",
    fTitle: "عنوان الدورة",
    fShort: "اسم البطاقة",
    fTagline: "الوصف القصير",
    fPrice: "السعر (ج.م)",
    fCompare: "السعر قبل الخصم (ج.م)",
    fCover: "مسار / رابط صورة الغلاف",
    addLessonLabel: "أضف درس فيديو",
    fLessonTitle: "عنوان الدرس",
    fLessonMins: "الدقائق",
    fLessonUrl: "رابط الفيديو (يوتيوب / MP4)",
    addLessonBtn: "إضافة درس +",
    extraCount: "دروس جديدة مضافة",
    resetCourse: "إعادة ضبط هذه الدورة",
    resetAll: "إعادة ضبط كل تعديلات الاستوديو",
    edited: "مُعدَّل",
    open: "عرض الصفحة",
    backToStudio: "→ الاستوديو",
    localNote: "استوديو تجريبي: التعديلات تُحفظ في هذا المتصفح وتغيّر الموقع مباشرة — الأسعار والبطاقات والدفع، كل شيء.",
    guard: "هذا المكتب يخص المدرّب.",
    guardSub: "سجّل الدخول بحساب المدير — أو عاين الاستوديو بنقرة واحدة.",
    guardCta: "معاينة كمدير ✦",
  },

  training: {
    kicker: "للشركات والفرق",
    titleA: "درّب",
    titleI: "الفريق كله",
    titleB: ".",
    sub: "برامج مخصصة للوكالات والاستوديوهات وفرق التسويق — علامات وحملات وموشن وإنتاج ذكاء اصطناعي. حضوريًا في مصر، وأونلاين مباشر في أي مكان آخر.",
    formTitle: "اطلب برنامجًا لفريقك",
    agency: "اسم الشركة / الوكالة",
    pName: "الشخص المسؤول",
    pNamePh: "من سأتحدث معه",
    pRole: "منصبه",
    pRoles: ["رئيس تنفيذي / مؤسس", "مدير تسويق", "مدير إبداعي / فني", "مسؤول موارد بشرية وتدريب", "قائد فريق", "أخرى"],
    size: "حجم الفريق",
    sizes: ["2–5", "6–15", "16–50", "+50"],
    industry: "المجال",
    industries: ["وكالة / استوديو", "عقارات", "مطاعم وضيافة", "أزياء وتجزئة", "تقنية / شركة ناشئة", "تعليم", "أخرى"],
    location: "الموقع",
    locations: ["مصر", "السعودية", "الإمارات", "الكويت", "قطر", "أخرى"],
    website: "رابط الموقع / البورتفوليو",
    modeLabel: "طريقة التنفيذ",
    modeEg: "🇪🇬 حضوريًا أو أونلاين مباشر — الخيار لك، ما دمت في مصر.",
    modeIntl: "🌍 أونلاين مباشر — البرنامج كامل عن بُعد للفرق خارج مصر.",
    submit: "اطلب البرنامج ←",
    note: "يفتح تطبيق بريدك وكل شيء مُعبّأ مسبقًا — أرد شخصيًا خلال 24 ساعة.",
    consultTitle: "استشارة استراتيجية مجانية",
    consultSub: "للرؤساء التنفيذيين والمؤسسين والمُلّاك ومديري التسويق: مكالمة مجانية — حتى 60 دقيقة — حول كيف يخفض إنتاج الذكاء الاصطناعي تكاليف محتواك ويسرّع إنتاجك. يسعدني المساعدة.",
    consultTag: "مجانًا · حتى 60 دقيقة",
    cName: "اسمك",
    cRole: "منصبك",
    cRoles: ["رئيس تنفيذي", "مؤسس / مالك", "مدير تسويق", "تنفيذي آخر"],
    cCompany: "الشركة",
    cContact: "بريد إلكتروني أو رقم واتساب",
    cTime: "الوقت المفضل",
    cTimes: ["صباحًا", "ظهرًا", "مساءً"],
    cSubmit: "احجز المكالمة المجانية ←",
    cNote: "يُحجز عبر واتساب — يصلك رد في اليوم نفسه.",
    tabProgram: "برنامج الفريق",
    tabConsult: "استشارة مجانية · 60 دقيقة",
    tabHint: "اختر مسارًا — نموذج واحد، دقيقتان.",
    bannerTag: "محمد طارق للأعمال",
  },

  contact: {
    metaTitle: "تواصل — تحدث مع المدرّب",
    kicker: "تواصل",
    titleA: "تحدث مع",
    titleI: "إنسان",
    titleB: ". معي أنا تحديدًا.",
    sub: "مساعدة في الاشتراك، تدريب الفرق، شراكات الأكاديميات، أو مجرد سؤال عن مسارك — أرد شخصيًا، غالبًا في اليوم نفسه.",
    waCta: "راسلني واتساب ←",
    emailCta: "راسلني بريدًا ←",
    formName: "اسمك",
    formEmail: "بريدك الإلكتروني",
    formTopic: "الموضوع",
    topics: ["سؤال عن دورة", "مساعدة في الاشتراك / الدفع", "تدريب فريق أو أكاديمية", "شيء آخر"],
    formMsg: "رسالتك",
    formSend: "أرسل الرسالة ←",
    formNote: "يفتح تطبيق بريدك وكل شيء مُعبّأ مسبقًا.",
    trainingTitle: "الشركات والأكاديميات",
    trainingNote: "برامج مخصصة للفرق — علامات وحملات وموشن وإنتاج ذكاء اصطناعي. حضوريًا في مصر، وأونلاين في أي مكان آخر.",
  },

  legal: {
    kicker: "قانوني",
    updated: "آخر تحديث",
    terms: {
      title: "شروط الخدمة",
      sections: [
        { h: "الخدمة", p: "تقدم المنصة تعليمًا للتصميم عبر الإنترنت: دروس فيديو ومشاريع وموارد واختبارات ومراجعات للمشاريع النهائية. الوصول إلى الدورات المدفوعة يُمنح للشخص بعد تأكيد الدفع وغير قابل للنقل أو المشاركة." },
        { h: "الاشتراك والوصول", p: "الاشتراكات المدفوعة تمنح وصولًا مدى الحياة للدورة المشتراة، شاملة تحديثاتها المستقبلية. الدورات المجانية قد تُحدَّث أو تُوسَّع أو يُعاد هيكلتها في أي وقت." },
        { h: "الاستخدام المقبول", p: "فيديوهات الدورات وملفاتها ومواردها مرخصة لك شخصيًا. إعادة التوزيع أو البيع أو التسجيل للمشاركة أو الرفع في مكان آخر يُنهي الوصول دون استرداد وقد يحمل تبعات قانونية." },
        { h: "الإكمال", p: "إكمال الدورة يعني إنهاء كل الدروس واجتياز اختبارات نقاط التفتيش وتسليم مشروع نهائي. المشاريع النهائية تتلقى مراجعة شخصية من المدرّب." },
        { h: "الاسترداد", p: "ضمان استرداد خلال 7 أيام يسري على الدورات المدفوعة — راجع سياسة الاسترداد للتفاصيل الدقيقة." },
        { h: "التغييرات", p: "قد تُحدَّث هذه الشروط؛ استمرار الاستخدام بعد التغييرات يعني القبول. التغييرات الجوهرية تُعلن على المنصة." },
      ],
    },
    privacy: {
      title: "سياسة الخصوصية",
      sections: [
        { h: "ما تخزنه هذه النسخة التجريبية", p: "تعمل المنصة حاليًا بالكامل في متصفحك: اسم حسابك وبريدك وتقدمك في الدورات ونتائج اختباراتك تُخزَّن في التخزين المحلي لمتصفحك فقط. لا يستقبل أي خادم هذه البيانات أو يعالجها أو يبيعها." },
        { h: "المدفوعات", p: "تتم المدفوعات عبر إنستا باي أو فودافون كاش أو (قريبًا) بوابات مرخصة. لا نرى أرقام البطاقات ولا نخزنها؛ تأكيد الدفع يتم عبر لقطات واتساب تختار أنت إرسالها." },
        { h: "التواصل", p: "محادثات واتساب والبريد تُستخدم فقط لتفعيل الوصول وتقديم الدعم و— بموافقتك فقط — مشاركة تحديثات الدورات." },
        { h: "التحليلات", p: "إن فُعِّلت التحليلات فهي مجمّعة ومجهولة: مشاهدات الصفحات وشعبية الدورات، وليست أبدًا بيانات تعلّم شخصية مرتبطة بهويتك." },
        { h: "حقوقك", p: "يمكنك مسح كل البيانات المخزنة محليًا في أي وقت من صفحة ملفك الشخصي، وطلب حذف أي سجل محادثات دعم عبر واتساب أو البريد." },
      ],
    },
    refunds: {
      title: "سياسة الاسترداد",
      sections: [
        { h: "الضمان", p: "كل دورة مدفوعة تحمل ضمان استرداد خلال 7 أيام، تُحسب من تفعيل الوصول. إن لم تناسبك، رسالة واتساب واحدة تعيد أموالك — بلا نماذج، بلا عناء." },
        { h: "كيف يعمل الاسترداد", p: "أرسل تفاصيل اشتراكك على واتساب خلال 7 أيام. تُعاد الأموال بنفس طريقة الدفع (إنستا باي / فودافون كاش) خلال 3 أيام عمل." },
        { h: "الاستخدام العادل", p: "الضمان موجود لإزالة المخاطرة لا لإعارة المحتوى: الحسابات التي تكمل أكثر من 60% من دورة أو تنزّل خزنة مواردها كاملة قبل طلب الاسترداد قد تُراجع فرديًا." },
        { h: "الحزم", p: "استرداد الحزم يعمل بالطريقة نفسها خلال نافذة الأيام السبعة. الاسترداد الجزئي (الاحتفاظ بدورة واحدة) يُعالج شخصيًا — فقط اسأل." },
      ],
    },
  },

  footer: {
    blurb: "محمد طارق هي المدرسة الرقمية للمدير الفني محمد طارق — دورات تصميم قصيرة راقية تنتهي بمشاريع حقيقية ومهارات حقيقية وبورتفوليو حقيقي.",
    learnCol: "تعلّم",
    platformCol: "الدعم",
    companyCol: "المدرسة",
    legalCol: "قانوني",
    connectCol: "تواصل",
    payLabel: "نقبل الدفع عبر",
    followLabel: "تابع الأعمال",
    rights: "جميع الحقوق محفوظة.",
    backTop: "العودة للأعلى ↑",
    madeIn: "يُدرَّس من مصر · موثوق عبر المنطقة",
  },

  notFound: {
    kicker: "404",
    titleA: "هذه الصفحة لم تجتز",
    titleI: "اختبار نقطة التفتيش",
    titleB: ".",
    sub: "الدرس الذي تبحث عنه انتقل أو تخرّج أو لم يشترك أصلًا. لنعدك إلى المسار.",
    home: "العودة للرئيسية ←",
    courses: "تصفّح الدورات",
  },
};

export const dict = { en, ar };
